/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author estra
 */
public class PanelRegistro extends javax.swing.JPanel {
    
        // ========== ATRIBUTOS ==========
    private VentanaPrincipal ventanaPrincipal;

    /**
     * Creates new form PanelRegistro
     */
    public PanelRegistro(VentanaPrincipal ventana) {
        this.ventanaPrincipal = ventana;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblConfirmarPassword = new javax.swing.JLabel();
        txtConfirmarPassword = new javax.swing.JPasswordField();
        btnRegistrarse = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(240, 240, 240));
        setPreferredSize(new java.awt.Dimension(900, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setText("Crear Nueva Cuenta");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 60, -1, -1));

        lblNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNombre.setText("Nombre completo");
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        txtNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNombre.setPreferredSize(new java.awt.Dimension(500, 35));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 165, -1, -1));

        lblEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEmail.setText("Email");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 215, -1, -1));

        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail.setPreferredSize(new java.awt.Dimension(500, 35));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        lblPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPassword.setText("Contraseña");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        txtPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPassword.setPreferredSize(new java.awt.Dimension(500, 35));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 325, -1, -1));

        lblConfirmarPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblConfirmarPassword.setText("Confirmar contraseña");
        add(lblConfirmarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 375, -1, -1));

        txtConfirmarPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtConfirmarPassword.setActionCommand("<Not Set>");
        txtConfirmarPassword.setPreferredSize(new java.awt.Dimension(500, 35));
        add(txtConfirmarPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        btnRegistrarse.setBackground(new java.awt.Color(102, 126, 234));
        btnRegistrarse.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.setPreferredSize(new java.awt.Dimension(240, 45));
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        btnVolver.setBackground(new java.awt.Color(158, 158, 158));
        btnVolver.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setPreferredSize(new java.awt.Dimension(240, 45));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        // Obtener datos ingresados
        String nombre = txtNombre.getText().trim();
        String email = txtEmail.getText().trim();
        String password = new String(txtPassword.getPassword());
        String confirmarPassword = new String(txtConfirmarPassword.getPassword());
        
        // Validar que no estén vacíos
        if (nombre.isEmpty() || email.isEmpty() || password.isEmpty() || confirmarPassword.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor, complete todos los campos", 
                "Campos vacíos", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Validar que las contraseñas coincidan
        if (!password.equals(confirmarPassword)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Las contraseñas no coinciden", 
                "Error de validación", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            txtPassword.setText("");
            txtConfirmarPassword.setText("");
            return;
        }
        
        // Validar longitud mínima de contraseña
        if (password.length() < 4) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "La contraseña debe tener al menos 4 caracteres", 
                "Contraseña débil", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Intentar registrar
        boolean registrado = ventanaPrincipal.getUsuarioManager().registrarUsuario(nombre, email, password);
        
        if (registrado) {
            // Registro exitoso
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Cuenta creada exitosamente. Ahora puede iniciar sesión", 
                "Registro exitoso", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            ventanaPrincipal.mostrarPanelLogin();
        } else {
            // Email ya existe
            javax.swing.JOptionPane.showMessageDialog(this, 
                "El email ya está registrado. Intente con otro o inicie sesión", 
                "Email duplicado", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            txtEmail.requestFocus(); // Poner cursor en email
        }
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ventanaPrincipal.mostrarPanelInicio();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblConfirmarPassword;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPasswordField txtConfirmarPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
