/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author estra
 */
public class PanelAdmin extends javax.swing.JPanel {
    
    // ========== ATRIBUTOS ==========
    private VentanaPrincipal ventanaPrincipal;
    private modelo.entidades.Usuario usuarioAdmin; 
    private modelo.gestores.ProductoManager productoManager;
    private modelo.gestores.UsuarioManager usuarioManager;

    /**
     * Creates new form PanelAdmin
     */
    public PanelAdmin(VentanaPrincipal ventana, modelo.entidades.Usuario admin, 
                  modelo.gestores.ProductoManager productoManager, 
                  modelo.gestores.UsuarioManager usuarioManager) {
        
        this.ventanaPrincipal = ventana;
        this.usuarioAdmin = admin;
        this.productoManager = productoManager;
        this.usuarioManager = usuarioManager;
        
        initComponents();
        
        // Mostrar panel de bienvenida por defecto
        mostrarBienvenida();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        btnGestionProductos = new javax.swing.JButton();
        btnVerUsuarios = new javax.swing.JButton();
        btnHistorialGlobal = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        panelContenido = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 590));
        setLayout(new java.awt.BorderLayout());

        panelMenu.setBackground(new java.awt.Color(220, 53, 69));
        panelMenu.setPreferredSize(new java.awt.Dimension(900, 60));

        btnGestionProductos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGestionProductos.setForeground(new java.awt.Color(220, 53, 69));
        btnGestionProductos.setText("Gestionar Productos");
        btnGestionProductos.setPreferredSize(new java.awt.Dimension(180, 40));
        btnGestionProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionProductosActionPerformed(evt);
            }
        });
        panelMenu.add(btnGestionProductos);

        btnVerUsuarios.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVerUsuarios.setForeground(new java.awt.Color(220, 35, 69));
        btnVerUsuarios.setText("Ver Usuarios");
        btnVerUsuarios.setPreferredSize(new java.awt.Dimension(150, 40));
        btnVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerUsuariosActionPerformed(evt);
            }
        });
        panelMenu.add(btnVerUsuarios);

        btnHistorialGlobal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnHistorialGlobal.setForeground(new java.awt.Color(220, 53, 69));
        btnHistorialGlobal.setText("Historial Global");
        btnHistorialGlobal.setPreferredSize(new java.awt.Dimension(150, 40));
        btnHistorialGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialGlobalActionPerformed(evt);
            }
        });
        panelMenu.add(btnHistorialGlobal);

        btnEstadisticas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEstadisticas.setForeground(new java.awt.Color(220, 53, 69));
        btnEstadisticas.setText("Estadisticas");
        btnEstadisticas.setPreferredSize(new java.awt.Dimension(150, 40));
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });
        panelMenu.add(btnEstadisticas);

        btnCerrarSesion.setBackground(new java.awt.Color(50, 50, 50));
        btnCerrarSesion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(150, 40));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        panelMenu.add(btnCerrarSesion);

        add(panelMenu, java.awt.BorderLayout.PAGE_START);

        panelContenido.setBackground(new java.awt.Color(255, 255, 255));
        panelContenido.setLayout(new java.awt.BorderLayout());
        add(panelContenido, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionProductosActionPerformed
        mostrarGestionProductos();
    }//GEN-LAST:event_btnGestionProductosActionPerformed

    private void btnVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerUsuariosActionPerformed
        mostrarVerUsuarios();
    }//GEN-LAST:event_btnVerUsuariosActionPerformed

    private void btnHistorialGlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialGlobalActionPerformed
        mostrarHistorialGlobal();
    }//GEN-LAST:event_btnHistorialGlobalActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        mostrarEstadisticas();
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        int confirmar = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Esta seguro que desea cerrar sesion?",
            "Confirmar",
            javax.swing.JOptionPane.YES_NO_OPTION
        );
    
        if(confirmar == javax.swing.JOptionPane.YES_OPTION){
            ventanaPrincipal.setUsuarioActual(null);
            ventanaPrincipal.mostrarPanelInicio();
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed
    // ========== MÉTODOS PARA CAMBIAR SUB-PANELES ==========

    private void mostrarSubPanel(javax.swing.JPanel subPanel) {
        panelContenido.removeAll();
        panelContenido.add(subPanel);
        panelContenido.revalidate();
        panelContenido.repaint();
    }

    private void mostrarBienvenida() {
        javax.swing.JPanel panelBienvenida = new javax.swing.JPanel();
        panelBienvenida.setBackground(java.awt.Color.WHITE);
        panelBienvenida.setLayout(new javax.swing.BoxLayout(panelBienvenida, javax.swing.BoxLayout.Y_AXIS));
    
        javax.swing.JLabel lblBienvenida = new javax.swing.JLabel("Bienvenido, " + usuarioAdmin.getNombre());
        lblBienvenida.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 28));
        lblBienvenida.setForeground(new java.awt.Color(220, 53, 69));
        lblBienvenida.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
    
        javax.swing.JLabel lblSubtitulo = new javax.swing.JLabel("Panel de Administrador");
        lblSubtitulo.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 18));
        lblSubtitulo.setForeground(new java.awt.Color(100, 100, 100));
        lblSubtitulo.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
    
        javax.swing.JLabel lblInstrucciones = new javax.swing.JLabel("Selecciona una opcion del menu superior");
        lblInstrucciones.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 14));
        lblInstrucciones.setForeground(new java.awt.Color(120, 120, 120));
        lblInstrucciones.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
    
        panelBienvenida.add(javax.swing.Box.createVerticalGlue());
        panelBienvenida.add(lblBienvenida);
        panelBienvenida.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 20)));
        panelBienvenida.add(lblSubtitulo);
        panelBienvenida.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 30)));
        panelBienvenida.add(lblInstrucciones);
        panelBienvenida.add(javax.swing.Box.createVerticalGlue());
    
        mostrarSubPanel(panelBienvenida);
    }

    private void mostrarGestionProductos() {
        mostrarSubPanel(new SubPanelGestionProductos(this, productoManager));
    }

    private void mostrarVerUsuarios() {
        mostrarSubPanel(new SubPanelUsuarios(this, usuarioManager));
    }

    private void mostrarHistorialGlobal() {
        mostrarSubPanel(new SubPanelHistorialGlobal(this, usuarioManager, productoManager));
    }

    private void mostrarEstadisticas() {
        mostrarSubPanel(new SubPanelEstadisticas(this, usuarioManager, productoManager));
    }

    // ========== GETTERS ==========

    public VentanaPrincipal getVentanaPrincipal() {
        return ventanaPrincipal;
    }
 
    public modelo.gestores.ProductoManager getProductoManager() {
        return productoManager;
    }

    public modelo.gestores.UsuarioManager getUsuarioManager() {
        return usuarioManager;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnGestionProductos;
    private javax.swing.JButton btnHistorialGlobal;
    private javax.swing.JButton btnVerUsuarios;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
