/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author estra
 */
public class PanelTienda extends javax.swing.JPanel {

    // ========== ATRIBUTOS ==========
    private VentanaPrincipal ventanaPrincipal;
    private modelo.entidades.Usuario usuarioActual;
    private modelo.gestores.ProductoManager productoManager;
    private modelo.gestores.CarritoManager carritoManager;
    private modelo.gestores.DeseosManager deseosManager;
    private modelo.gestores.HistorialManager historialManager;
    /**
     * Creates new form PanelTienda
     */
    public PanelTienda(VentanaPrincipal ventana, modelo.entidades.Usuario usuario, modelo.gestores.ProductoManager productoManager) {
        this.ventanaPrincipal = ventana;
        this.usuarioActual = usuario;
        this.productoManager = productoManager;
        
        // Inicializar managers específicos del usuario
        this.carritoManager = new modelo.gestores.CarritoManager(usuario.getNombre(), productoManager);
        this.deseosManager = new modelo.gestores.DeseosManager(usuario.getNombre(), productoManager);
        this.historialManager = new modelo.gestores.HistorialManager(usuario.getNombre(), productoManager);
        
        initComponents();
        
        //mostrar catalogo por defecto
        mostrarCatalogo();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        btnCatalogo = new javax.swing.JButton();
        btnCarrito = new javax.swing.JButton();
        btnDeseos = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        panelContenido = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 650));
        setLayout(new java.awt.BorderLayout());

        panelMenu.setBackground(new java.awt.Color(102, 126, 234));
        panelMenu.setPreferredSize(new java.awt.Dimension(900, 60));

        btnCatalogo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCatalogo.setForeground(new java.awt.Color(102, 126, 234));
        btnCatalogo.setText("Catálogo");
        btnCatalogo.setPreferredSize(new java.awt.Dimension(150, 40));
        btnCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoActionPerformed(evt);
            }
        });
        panelMenu.add(btnCatalogo);

        btnCarrito.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCarrito.setForeground(new java.awt.Color(102, 126, 234));
        btnCarrito.setText("Carrito");
        btnCarrito.setPreferredSize(new java.awt.Dimension(150, 40));
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });
        panelMenu.add(btnCarrito);

        btnDeseos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDeseos.setForeground(new java.awt.Color(102, 126, 234));
        btnDeseos.setText("Deseos");
        btnDeseos.setPreferredSize(new java.awt.Dimension(150, 40));
        btnDeseos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeseosActionPerformed(evt);
            }
        });
        panelMenu.add(btnDeseos);

        btnHistorial.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnHistorial.setForeground(new java.awt.Color(102, 126, 234));
        btnHistorial.setText("Historial");
        btnHistorial.setPreferredSize(new java.awt.Dimension(150, 40));
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        panelMenu.add(btnHistorial);

        btnCerrarSesion.setBackground(new java.awt.Color(250, 100, 100));
        btnCerrarSesion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(170, 40));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        panelMenu.add(btnCerrarSesion);

        add(panelMenu, java.awt.BorderLayout.PAGE_START);

        panelContenido.setBackground(new java.awt.Color(255, 255, 255));
        panelContenido.setLayout(new java.awt.BorderLayout());
        add(panelContenido, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

   // ========== MÉTODOS PARA CAMBIAR SUB-PANELES ==========
    
    private void mostrarSubPanel(javax.swing.JPanel subPanel) {
        panelContenido.removeAll();
        panelContenido.add(subPanel);
        panelContenido.revalidate();
        panelContenido.repaint();
    }
    
    private void mostrarCatalogo() {
    // ✅ USAR SubPanelCatalogo en lugar del panel temporal
        SubPanelCatalogo subPanelCatalogo = new SubPanelCatalogo(
            this, 
            productoManager, 
            carritoManager, 
            deseosManager
        );
        mostrarSubPanel(subPanelCatalogo);
    }
    
    private void mostrarCarrito() {
        SubPanelCarrito subPanelCarrito = new SubPanelCarrito(
            this,
            carritoManager,
            productoManager
        );
        mostrarSubPanel(subPanelCarrito);
    }
    
    private void mostrarDeseos() {
        SubPanelDeseos subPanelDeseos = new SubPanelDeseos(
            this,
            deseosManager,
            carritoManager,
            productoManager
        );
        mostrarSubPanel(subPanelDeseos);
    }

    
    public void mostrarHistorial() {
        SubPanelHistorial subPanelHistorial = new SubPanelHistorial(
            this,
            historialManager
        );
        mostrarSubPanel(subPanelHistorial);
    }
    
    // ========== MÉTODO PARA REGISTRAR COMPRA EN HISTORIAL ==========

    public void registrarCompraEnHistorial(java.util.List<modelo.entidades.ItemCarrito> items, double total) {
        historialManager.agregarCompra(items, total);
    }

    private void btnCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoActionPerformed
        mostrarCatalogo();
    }//GEN-LAST:event_btnCatalogoActionPerformed

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        mostrarCarrito();
    }//GEN-LAST:event_btnCarritoActionPerformed

    private void btnDeseosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeseosActionPerformed
        mostrarDeseos();
    }//GEN-LAST:event_btnDeseosActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        mostrarHistorial();
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        int confirmar = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Está seguro que desea cerrar sesión?",
                "confirmar",
                javax.swing.JOptionPane.YES_NO_OPTION);
        
        if(confirmar == javax.swing.JOptionPane.YES_OPTION){
            ventanaPrincipal.setUsuarioActual(null);
            ventanaPrincipal.mostrarPanelInicio();
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrito;
    private javax.swing.JButton btnCatalogo;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnDeseos;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
