/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author estra
 */
public class PanelLogin extends javax.swing.JPanel {

     // ========== ATRIBUTOS ==========
    private VentanaPrincipal ventanaPrincipal;
    
    
    /**
     * Creates new form PanelLogin
     */
    public PanelLogin(VentanaPrincipal ventana) {
        this.ventanaPrincipal = ventana;
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(240, 240, 240));
        setPreferredSize(new java.awt.Dimension(900, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(50, 50, 50));
        lblTitulo.setText("Iniciar Sesión");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        lblEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEmail.setText("Email o Usuario");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        txtEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtEmail.setPreferredSize(new java.awt.Dimension(500, 35));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        lblPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPassword.setText("Contraseña");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        txtPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPassword.setPreferredSize(new java.awt.Dimension(500, 35));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        btnEntrar.setBackground(new java.awt.Color(102, 126, 234));
        btnEntrar.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setLabel("Entrar");
        btnEntrar.setPreferredSize(new java.awt.Dimension(240, 45));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        btnVolver.setBackground(new java.awt.Color(158, 158, 158));
        btnVolver.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setPreferredSize(new java.awt.Dimension(240, 45));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        String email = txtEmail.getText().trim();
        String password = new String(txtPassword.getPassword());
    
    // Validar que no estén vacíos
        if (email.isEmpty() || password.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor, complete todos los campos", 
                "Campos vacíos", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        modelo.entidades.Usuario usuario = ventanaPrincipal.getUsuarioManager().login(email, password);
    
    if (usuario != null) {
        // Login exitoso
        ventanaPrincipal.setUsuarioActual(usuario);
        ventanaPrincipal.mostrarPanelTienda();
    } else {
        // Login fallido
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Email o contraseña incorrectos", 
            "Error de login", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        txtPassword.setText(""); // Limpiar contraseña
    }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ventanaPrincipal.mostrarPanelInicio();
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
