/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author estra
 */
public class SubPanelUsuarios extends javax.swing.JPanel {
    
    // ========== ATRIBUTOS ==========
    private PanelAdmin panelAdmin;
    private modelo.gestores.UsuarioManager usuarioManager;
    private javax.swing.table.DefaultTableModel modeloTabla;

    /**
     * Creates new form SubPanelUsuarios
     */
    public SubPanelUsuarios(PanelAdmin panelAdmin, modelo.gestores.UsuarioManager usuarioManager) {
        this.panelAdmin = panelAdmin;
        this.usuarioManager = usuarioManager;
    
        initComponents();
        configurarTabla();
        cargarUsuariosEnTabla();
        actualizarEstadisticas();
    }
    
    // ========== MÉTODOS ==========

    private void configurarTabla() {
        String[] columnas = {"Nombre", "Email", "Rol"};
        modeloTabla = new javax.swing.table.DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
    
        tablaUsuarios.setModel(modeloTabla);
        tablaUsuarios.setAutoCreateRowSorter(true);
        tablaUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaUsuarios.setRowHeight(30);
    
        // Ajustar ancho de columnas
        tablaUsuarios.getColumnModel().getColumn(0).setPreferredWidth(200);
        tablaUsuarios.getColumnModel().getColumn(1).setPreferredWidth(300);
        tablaUsuarios.getColumnModel().getColumn(2).setPreferredWidth(150);
    }

    private void cargarUsuariosEnTabla() {
        modeloTabla.setRowCount(0);
    
        java.util.List<modelo.entidades.Usuario> usuarios = usuarioManager.obtenerTodosUsuarios();
     
        for (modelo.entidades.Usuario usuario : usuarios) {
            Object[] fila = {
                usuario.getNombre(),
                usuario.getEmail(),
                usuario.getRol().equalsIgnoreCase("admin") ? "Administrador" : "Usuario"
            };
            modeloTabla.addRow(fila);
        }
    }

    private void actualizarEstadisticas() {
        java.util.List<modelo.entidades.Usuario> usuarios = usuarioManager.obtenerTodosUsuarios();
    
        int totalUsuarios = usuarios.size();
        int totalAdmins = 0;
        int totalUsuariosNormales = 0;
    
        for (modelo.entidades.Usuario usuario : usuarios) {
            if (usuario.esAdministrador()) {
                totalAdmins++;
            } else {
                totalUsuariosNormales++;
            }
        }
    
        lblTotalUsuarios.setText("Total Usuarios: " + totalUsuarios);
        lblTotalAdmins.setText("Administradores: " + totalAdmins);
        lblTotalUsuariosNormales.setText("Usuarios Normales: " + totalUsuariosNormales);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        lblTotalUsuarios = new javax.swing.JLabel();
        lblTotalAdmins = new javax.swing.JLabel();
        lblTotalUsuariosNormales = new javax.swing.JLabel();
        scrollTabla = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 590));
        setLayout(new java.awt.BorderLayout());

        panelSuperior.setBackground(new java.awt.Color(220, 53, 69));
        panelSuperior.setPreferredSize(new java.awt.Dimension(900, 60));
        panelSuperior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 10));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Usuraios Registrados");
        panelSuperior.add(lblTitulo);

        add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelInferior.setBackground(new java.awt.Color(236, 240, 241));
        panelInferior.setPreferredSize(new java.awt.Dimension(900, 80));
        panelInferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 15));

        lblTotalUsuarios.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTotalUsuarios.setForeground(new java.awt.Color(52, 73, 94));
        lblTotalUsuarios.setText("Total Usuarios: 0");
        panelInferior.add(lblTotalUsuarios);

        lblTotalAdmins.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTotalAdmins.setForeground(new java.awt.Color(220, 53, 69));
        lblTotalAdmins.setText("Total Administradores: 0");
        panelInferior.add(lblTotalAdmins);

        lblTotalUsuariosNormales.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTotalUsuariosNormales.setForeground(new java.awt.Color(39, 174, 96));
        lblTotalUsuariosNormales.setText("Usuarios Normales: 0");
        panelInferior.add(lblTotalUsuariosNormales);

        add(panelInferior, java.awt.BorderLayout.PAGE_END);

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTabla.setViewportView(tablaUsuarios);

        add(scrollTabla, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalAdmins;
    private javax.swing.JLabel lblTotalUsuarios;
    private javax.swing.JLabel lblTotalUsuariosNormales;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
