/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author estra
 */
public class SubPanelDeseos extends javax.swing.JPanel {
    
    // ========== ATRIBUTOS ==========
    private PanelTienda panelTienda;
    private modelo.gestores.DeseosManager deseosManager;
    private modelo.gestores.CarritoManager carritoManager;
    private modelo.gestores.ProductoManager productoManager;

    /**
     * Creates new form SubPanelDeseos
     */
    public SubPanelDeseos(PanelTienda panelTienda, modelo.gestores.DeseosManager deseosManager,
                          modelo.gestores.CarritoManager carritoManager, modelo.gestores.ProductoManager productoManager) {
        
        this.panelTienda = panelTienda;
        this.deseosManager = deseosManager;
        this.carritoManager = carritoManager;
        this.productoManager = productoManager;
        
        initComponents();
        
        // Configurar BoxLayout para panelDeseos (vertical)
        panelDeseos.setLayout(new javax.swing.BoxLayout(panelDeseos, javax.swing.BoxLayout.Y_AXIS));
        
        // Cargar productos de la lista de deseos
        cargarDeseos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInferior = new javax.swing.JPanel();
        btnVaciarDeseos = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        panelDeseos = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 590));
        setLayout(new java.awt.BorderLayout());

        panelInferior.setBackground(new java.awt.Color(102, 126, 234));
        panelInferior.setPreferredSize(new java.awt.Dimension(900, 70));

        btnVaciarDeseos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVaciarDeseos.setForeground(new java.awt.Color(102, 126, 234));
        btnVaciarDeseos.setText("Vaciar Lista de Deseos");
        btnVaciarDeseos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVaciarDeseos.setPreferredSize(new java.awt.Dimension(220, 40));
        btnVaciarDeseos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarDeseosActionPerformed(evt);
            }
        });
        panelInferior.add(btnVaciarDeseos);

        add(panelInferior, java.awt.BorderLayout.PAGE_END);

        panelDeseos.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setViewportView(panelDeseos);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVaciarDeseosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarDeseosActionPerformed
        vaciarListaDeDeseos();
    }//GEN-LAST:event_btnVaciarDeseosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVaciarDeseos;
    private javax.swing.JPanel panelDeseos;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
    // ========== MÉTODOS PARA CARGAR Y MOSTRAR DESEOS ==========
    
    private void cargarDeseos() {
        // Limpiar panel
        panelDeseos.removeAll();
        
        java.util.List<modelo.entidades.Producto> productos = deseosManager.obtenerDeseos();
        
        if (productos.isEmpty()) {
            // Mostrar mensaje de lista vacía
            javax.swing.JLabel lblVacio = new javax.swing.JLabel("Tu lista de deseos está vacía");
            lblVacio.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            lblVacio.setForeground(new java.awt.Color(150, 150, 150));
            lblVacio.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
            
            javax.swing.JLabel lblMensaje = new javax.swing.JLabel("Agrega productos desde el catálogo");
            lblMensaje.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 14));
            lblMensaje.setForeground(new java.awt.Color(120, 120, 120));
            lblMensaje.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
            
            panelDeseos.add(javax.swing.Box.createVerticalGlue());
            panelDeseos.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 20)));
            panelDeseos.add(lblVacio);
            panelDeseos.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
            panelDeseos.add(lblMensaje);
            panelDeseos.add(javax.swing.Box.createVerticalGlue());
            
            // Deshabilitar botón de vaciar
            btnVaciarDeseos.setEnabled(false);
        } else {
            // Crear tarjetas para cada producto
            for (modelo.entidades.Producto producto : productos) {
                panelDeseos.add(crearTarjetaDeseo(producto));
                panelDeseos.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
            }
            
            // Habilitar botón de vaciar
            btnVaciarDeseos.setEnabled(true);
        }
        
        panelDeseos.revalidate();
        panelDeseos.repaint();
    }
    
    private javax.swing.JPanel crearTarjetaDeseo(modelo.entidades.Producto producto) {
        javax.swing.JPanel tarjeta = new javax.swing.JPanel();
        tarjeta.setLayout(new java.awt.BorderLayout(15, 15));
        tarjeta.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1),
            javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)
        ));
        tarjeta.setBackground(java.awt.Color.WHITE);
        tarjeta.setMaximumSize(new java.awt.Dimension(850, 140));
        
        // Panel izquierdo: Imagen
        javax.swing.JPanel panelImagen = crearPanelImagenDeseo(producto);
        tarjeta.add(panelImagen, java.awt.BorderLayout.WEST);
        
        // Panel central: Información
        javax.swing.JPanel panelInfo = crearPanelInfoDeseo(producto);
        tarjeta.add(panelInfo, java.awt.BorderLayout.CENTER);
        
        // Panel derecho: Botones de acción
        javax.swing.JPanel panelAcciones = crearPanelAccionesDeseo(producto);
        tarjeta.add(panelAcciones, java.awt.BorderLayout.EAST);
        
        return tarjeta;
    }
    
    private javax.swing.JPanel crearPanelImagenDeseo(modelo.entidades.Producto producto) {
        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setLayout(new java.awt.BorderLayout());
        panel.setPreferredSize(new java.awt.Dimension(100, 100));
        panel.setBackground(java.awt.Color.WHITE);
        
        javax.swing.JLabel lblImagen = new javax.swing.JLabel();
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setOpaque(true);
        lblImagen.setBackground(new java.awt.Color(240, 240, 250));
        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1));
        
        // Cargar imagen
        try {
            String rutaImagen = producto.getImagenActual();
            java.io.File archivoImagen = new java.io.File(rutaImagen);
            
            if (archivoImagen.exists()) {
                javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(rutaImagen);
                java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(
                    90, 90, java.awt.Image.SCALE_SMOOTH
                );
                lblImagen.setIcon(new javax.swing.ImageIcon(imagenEscalada));
            } else {
                // Emoji por defecto
                lblImagen.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 40));
                lblImagen.setText(obtenerEmojiPorCategoria(producto.getCategoria()));
            }
        } catch (Exception e) {
            lblImagen.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 40));
            lblImagen.setText(obtenerEmojiPorCategoria(producto.getCategoria()));
        }
        
        panel.add(lblImagen, java.awt.BorderLayout.CENTER);
        return panel;
    }
    
    private javax.swing.JPanel crearPanelInfoDeseo(modelo.entidades.Producto producto) {
        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.Y_AXIS));
        panel.setBackground(java.awt.Color.WHITE);
        
        // Nombre
        javax.swing.JLabel lblNombre = new javax.swing.JLabel(producto.getNombre());
        lblNombre.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        lblNombre.setAlignmentX(javax.swing.JComponent.LEFT_ALIGNMENT);
        
        // Precio
        javax.swing.JLabel lblPrecio = new javax.swing.JLabel(
            String.format("Precio: $%.2f", producto.getPrecio())
        );
        lblPrecio.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 15));
        lblPrecio.setForeground(new java.awt.Color(102, 126, 234));
        lblPrecio.setAlignmentX(javax.swing.JComponent.LEFT_ALIGNMENT);
        
        // Categoría
        javax.swing.JLabel lblCategoria = new javax.swing.JLabel(
            "Categoría: " + producto.getCategoria()
        );
        lblCategoria.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 12));
        lblCategoria.setForeground(new java.awt.Color(120, 120, 120));
        lblCategoria.setAlignmentX(javax.swing.JComponent.LEFT_ALIGNMENT);
        
        // Stock disponible
        String textoStock = producto.getStock() > 0 
            ? "Stock: " + producto.getStock() + " unidades disponibles"
            : "Sin stock disponible";
        
        javax.swing.JLabel lblStock = new javax.swing.JLabel(textoStock);
        lblStock.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 11));
        lblStock.setForeground(
            producto.getStock() > 0 
                ? new java.awt.Color(0, 150, 0) 
                : new java.awt.Color(200, 0, 0)
        );
        lblStock.setAlignmentX(javax.swing.JComponent.LEFT_ALIGNMENT);
        
        panel.add(lblNombre);
        panel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 8)));
        panel.add(lblPrecio);
        panel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
        panel.add(lblCategoria);
        panel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
        panel.add(lblStock);
        
        return panel;
    }
    
    private javax.swing.JPanel crearPanelAccionesDeseo(modelo.entidades.Producto producto) {
        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.Y_AXIS));
        panel.setBackground(java.awt.Color.WHITE);
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        // Botón Agregar al Carrito
        javax.swing.JButton btnAgregarCarrito = new javax.swing.JButton("Al Carrito");
        btnAgregarCarrito.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
        btnAgregarCarrito.setBackground(new java.awt.Color(102, 126, 234));
        btnAgregarCarrito.setForeground(java.awt.Color.WHITE);
        btnAgregarCarrito.setFocusPainted(false);
        btnAgregarCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarCarrito.setMaximumSize(new java.awt.Dimension(140, 35));
        btnAgregarCarrito.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
        btnAgregarCarrito.addActionListener(e -> agregarAlCarritoDesdeDeseos(producto));
        
        // Deshabilitar si no hay stock
        if (producto.getStock() <= 0) {
            btnAgregarCarrito.setEnabled(false);
            btnAgregarCarrito.setText("Sin stock");
        }
        
        // Botón Eliminar de Deseos
        javax.swing.JButton btnEliminar = new javax.swing.JButton("Quitar");
        btnEliminar.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
        btnEliminar.setBackground(new java.awt.Color(220, 53, 69));
        btnEliminar.setForeground(java.awt.Color.WHITE);
        btnEliminar.setFocusPainted(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setMaximumSize(new java.awt.Dimension(140, 35));
        btnEliminar.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
        btnEliminar.addActionListener(e -> eliminarDeDeseos(producto));
        
        panel.add(btnAgregarCarrito);
        panel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
        panel.add(btnEliminar);
        panel.add(javax.swing.Box.createVerticalGlue());
        
        return panel;
    }
    
    // ========== MÉTODOS DE ACCIONES ==========
    
    private void agregarAlCarritoDesdeDeseos(modelo.entidades.Producto producto) {
        if (producto.getStock() <= 0) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Este producto no tiene stock disponible",
                "Sin stock",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }
    
        // Verificar si el producto ya está en el carrito
        if (carritoManager.productoExisteEnCarrito(producto.getId())) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Este producto ya está en tu carrito",
                "Aviso",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }
    
        // Agregar al carrito
        carritoManager.agregarAlCarrito(producto, 1);
    
        // Mostrar notificación de éxito
        javax.swing.JOptionPane.showMessageDialog(
            this,
            producto.getNombre() + " agregado al carrito",
            "Éxito",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    
        // Preguntar si quiere eliminar de deseos
        int eliminar = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Deseas quitar este producto de tu lista de deseos?",
            "Quitar de deseos",
            javax.swing.JOptionPane.YES_NO_OPTION
        );
    
        if (eliminar == javax.swing.JOptionPane.YES_OPTION) {
            deseosManager.eliminarDeDeseos(producto.getId());
            cargarDeseos(); // Recargar vista
        }
    }
    
    private void eliminarDeDeseos(modelo.entidades.Producto producto) {
        int confirmar = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de quitar \"" + producto.getNombre() + "\" de tu lista de deseos?",
            "Confirmar",
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        
        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
            deseosManager.eliminarDeDeseos(producto.getId());
            cargarDeseos();
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Producto eliminado de la lista de deseos",
                "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
        }
    }
    
    private void vaciarListaDeDeseos() {
        if (deseosManager.estaVacio()) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Tu lista de deseos ya está vacía",
                "Lista vacía",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }
        
        int confirmar = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de vaciar toda tu lista de deseos?",
            "Confirmar",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
        
        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
            // Eliminar todos los productos de deseos
            java.util.List<modelo.entidades.Producto> productos = deseosManager.obtenerDeseos();
            for (modelo.entidades.Producto producto : productos) {
                deseosManager.eliminarDeDeseos(producto.getId());
            }
            
            cargarDeseos();
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Lista de deseos vaciada exitosamente",
                "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
        }
    }
    
    // ========== MÉTODO AUXILIAR ==========
    
    private String obtenerEmojiPorCategoria(String categoria) {
        return "Sin imagen disponible";
    }
}
