/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author estra
 */
public class SubPanelCarrito extends javax.swing.JPanel {
    
    // ========== ATRIBUTOS ==========
    private PanelTienda panelTienda;
    private modelo.gestores.CarritoManager carritoManager;
    private modelo.gestores.ProductoManager productoManager;

    /**
     * Creates new form SubPanelCarrito
     */
    public SubPanelCarrito(PanelTienda panelTienda, modelo.gestores.CarritoManager carritoManager,
                           modelo.gestores.ProductoManager productoManager) {
        
        this.panelTienda = panelTienda;
        this.carritoManager = carritoManager;
        this.productoManager = productoManager;
        initComponents();
        
        // Configurar BoxLayout para panelItems (vertical)
        panelItems.setLayout(new javax.swing.BoxLayout(panelItems, javax.swing.BoxLayout.Y_AXIS));
        
        // Cargar items del carrito
        cargarCarrito();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInferior = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        btnVaciarCarrito = new javax.swing.JButton();
        btnFinalizarCompra = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        panelItems = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 590));
        setLayout(new java.awt.BorderLayout());

        panelInferior.setBackground(new java.awt.Color(102, 126, 234));
        panelInferior.setPreferredSize(new java.awt.Dimension(900, 100));

        lblTotal.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("Total: $0.00");
        panelInferior.add(lblTotal);

        btnVaciarCarrito.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVaciarCarrito.setForeground(new java.awt.Color(102, 126, 234));
        btnVaciarCarrito.setText("Vaciar Carrito");
        btnVaciarCarrito.setPreferredSize(new java.awt.Dimension(150, 40));
        btnVaciarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarCarritoActionPerformed(evt);
            }
        });
        panelInferior.add(btnVaciarCarrito);

        btnFinalizarCompra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnFinalizarCompra.setForeground(new java.awt.Color(102, 126, 234));
        btnFinalizarCompra.setText("Finalizar Compra");
        btnFinalizarCompra.setPreferredSize(new java.awt.Dimension(180, 40));
        btnFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCompraActionPerformed(evt);
            }
        });
        panelInferior.add(btnFinalizarCompra);

        add(panelInferior, java.awt.BorderLayout.PAGE_END);

        panelItems.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setViewportView(panelItems);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCompraActionPerformed
        finalizarCompra();
    }//GEN-LAST:event_btnFinalizarCompraActionPerformed

    private void btnVaciarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarCarritoActionPerformed
        vaciarCarritoCompleto();
    }//GEN-LAST:event_btnVaciarCarritoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarCompra;
    private javax.swing.JButton btnVaciarCarrito;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelItems;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
    // ========== MÉTODOS PARA CARGAR Y MOSTRAR CARRITO ==========
    
    private void cargarCarrito() {
        // Limpiar panel
        panelItems.removeAll();
        
        java.util.List<modelo.entidades.ItemCarrito> items = carritoManager.obtenerCarrito();
        
        if (items.isEmpty()) {
            // Mostrar mensaje de carrito vacío
            javax.swing.JLabel lblVacio = new javax.swing.JLabel("Tu carrito está vacío");
            lblVacio.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            lblVacio.setForeground(new java.awt.Color(150, 150, 150));
            lblVacio.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
            
            javax.swing.JLabel lblEmoji = new javax.swing.JLabel("🛒");
            lblEmoji.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 80));
            lblEmoji.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
            
            panelItems.add(javax.swing.Box.createVerticalGlue());
            panelItems.add(lblEmoji);
            panelItems.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 20)));
            panelItems.add(lblVacio);
            panelItems.add(javax.swing.Box.createVerticalGlue());
            
            // Deshabilitar botón de compra
            btnFinalizarCompra.setEnabled(false);
        } else {
            // Crear tarjetas para cada item
            for (int i = 0; i < items.size(); i++) {
                panelItems.add(crearTarjetaItem(items.get(i), i));
                panelItems.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
            }
            
            // Habilitar botón de compra
            btnFinalizarCompra.setEnabled(true);
        }
        
        // Actualizar total
        actualizarTotal();
        
        panelItems.revalidate();
        panelItems.repaint();
    }
    
    private javax.swing.JPanel crearTarjetaItem(modelo.entidades.ItemCarrito item, int indice) {
        javax.swing.JPanel tarjeta = new javax.swing.JPanel();
        tarjeta.setLayout(new java.awt.BorderLayout(15, 15));
        tarjeta.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1),
            javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)
        ));
        tarjeta.setBackground(java.awt.Color.WHITE);
        tarjeta.setMaximumSize(new java.awt.Dimension(850, 150));
        
        modelo.entidades.Producto producto = item.getProducto();
        
        // Panel izquierdo: Imagen
        javax.swing.JPanel panelImagen = crearPanelImagenCarrito(producto);
        tarjeta.add(panelImagen, java.awt.BorderLayout.WEST);
        
        // Panel central: Información
        javax.swing.JPanel panelInfo = crearPanelInfoCarrito(item);
        tarjeta.add(panelInfo, java.awt.BorderLayout.CENTER);
        
        // Panel derecho: Controles (cantidad y eliminar)
        javax.swing.JPanel panelControles = crearPanelControles(item, indice);
        tarjeta.add(panelControles, java.awt.BorderLayout.EAST);
        
        return tarjeta;
    }
    
    private javax.swing.JPanel crearPanelImagenCarrito(modelo.entidades.Producto producto) {
        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setLayout(new java.awt.BorderLayout());
        panel.setPreferredSize(new java.awt.Dimension(100, 100));
        panel.setBackground(java.awt.Color.WHITE);
        
        javax.swing.JLabel lblImagen = new javax.swing.JLabel();
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setOpaque(true);
        lblImagen.setBackground(new java.awt.Color(240, 240, 250));
        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1));
        
        // Cargar imagen
        try {
            String rutaImagen = producto.getImagenActual();
            java.io.File archivoImagen = new java.io.File(rutaImagen);
            
            if (archivoImagen.exists()) {
                javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(rutaImagen);
                java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(
                    90, 90, java.awt.Image.SCALE_SMOOTH
                );
                lblImagen.setIcon(new javax.swing.ImageIcon(imagenEscalada));
            } else {
                // Emoji por defecto
                lblImagen.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 40));
                lblImagen.setText(obtenerEmojiPorCategoria(producto.getCategoria()));
            }
        } catch (Exception e) {
            lblImagen.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 40));
            lblImagen.setText(obtenerEmojiPorCategoria(producto.getCategoria()));
        }
        
        panel.add(lblImagen, java.awt.BorderLayout.CENTER);
        return panel;
    }
    
    private javax.swing.JPanel crearPanelInfoCarrito(modelo.entidades.ItemCarrito item) {
        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.Y_AXIS));
        panel.setBackground(java.awt.Color.WHITE);
        
        modelo.entidades.Producto producto = item.getProducto();
        
        // Nombre
        javax.swing.JLabel lblNombre = new javax.swing.JLabel(producto.getNombre());
        lblNombre.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        lblNombre.setAlignmentX(javax.swing.JComponent.LEFT_ALIGNMENT);
        
        // Precio unitario
        javax.swing.JLabel lblPrecio = new javax.swing.JLabel(
            String.format("Precio unitario: $%.2f", producto.getPrecio())
        );
        lblPrecio.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 13));
        lblPrecio.setForeground(new java.awt.Color(100, 100, 100));
        lblPrecio.setAlignmentX(javax.swing.JComponent.LEFT_ALIGNMENT);
        
        // Subtotal
        javax.swing.JLabel lblSubtotal = new javax.swing.JLabel(
            String.format("Subtotal: $%.2f", item.getSubtotal())
        );
        lblSubtotal.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 15));
        lblSubtotal.setForeground(new java.awt.Color(102, 126, 234));
        lblSubtotal.setAlignmentX(javax.swing.JComponent.LEFT_ALIGNMENT);
        
        // Stock disponible
        javax.swing.JLabel lblStock = new javax.swing.JLabel(
            "Disponibles: " + producto.getStock() + " unidades"
        );
        lblStock.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 11));
        lblStock.setForeground(new java.awt.Color(120, 120, 120));
        lblStock.setAlignmentX(javax.swing.JComponent.LEFT_ALIGNMENT);
        
        panel.add(lblNombre);
        panel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 8)));
        panel.add(lblPrecio);
        panel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
        panel.add(lblSubtotal);
        panel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
        panel.add(lblStock);
        
        return panel;
    }
    
    private javax.swing.JPanel crearPanelControles(modelo.entidades.ItemCarrito item, int indice) {
        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.Y_AXIS));
        panel.setBackground(java.awt.Color.WHITE);
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        // Label "Cantidad"
        javax.swing.JLabel lblCantidad = new javax.swing.JLabel("Cantidad:");
        lblCantidad.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
        lblCantidad.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
        
        // Spinner para cantidad
        javax.swing.SpinnerNumberModel modeloSpinner = new javax.swing.SpinnerNumberModel(
            item.getCantidad(),  // valor inicial
            1,                   // mínimo
            item.getProducto().getStock(),  // máximo (stock disponible)
            1                    // step
        );
        javax.swing.JSpinner spinnerCantidad = new javax.swing.JSpinner(modeloSpinner);
        spinnerCantidad.setMaximumSize(new java.awt.Dimension(80, 30));
        spinnerCantidad.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 13));
        
        // Listener para cuando cambia la cantidad
        spinnerCantidad.addChangeListener(e -> {
            int nuevaCantidad = (Integer) spinnerCantidad.getValue();
            item.setCantidad(nuevaCantidad);
            carritoManager.guardarCarritoEnArchivo();
            cargarCarrito(); // Recargar vista
        });
        
        // Botón eliminar
        javax.swing.JButton btnEliminar = new javax.swing.JButton("🗑️ Eliminar");
        btnEliminar.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 11));
        btnEliminar.setBackground(new java.awt.Color(220, 53, 69));
        btnEliminar.setForeground(java.awt.Color.WHITE);
        btnEliminar.setFocusPainted(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setMaximumSize(new java.awt.Dimension(120, 30));
        btnEliminar.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
        btnEliminar.addActionListener(e -> eliminarItem(indice));
        
        panel.add(lblCantidad);
        panel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
        panel.add(spinnerCantidad);
        panel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 15)));
        panel.add(btnEliminar);
        panel.add(javax.swing.Box.createVerticalGlue());
        
        return panel;
    }
    
    // ========== MÉTODOS DE ACCIONES ==========
    
    private void eliminarItem(int indice) {
        int confirmar = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de eliminar este producto del carrito?",
            "Confirmar eliminación",
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        
        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
            carritoManager.eliminarDelCarrito(indice);
            cargarCarrito();
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Producto eliminado del carrito",
                "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
        }
    }
    
    private void vaciarCarritoCompleto() {
        if (carritoManager.estaVacio()) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "El carrito ya está vacío",
                "Carrito vacío",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }
        
        int confirmar = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Estás seguro de vaciar todo el carrito?",
            "Confirmar",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
        
        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
            carritoManager.vaciarCarrito();
            cargarCarrito();
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Carrito vaciado exitosamente",
                "Éxito",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
        }
    }
    
    private void finalizarCompra() {
        if (carritoManager.estaVacio()) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Tu carrito está vacío. Agrega productos para comprar.",
                "Carrito vacío",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        // Validar stock de todos los productos
        java.util.List<modelo.entidades.ItemCarrito> items = carritoManager.obtenerCarrito();
        for (modelo.entidades.ItemCarrito item : items) {
            if (item.getCantidad() > item.getProducto().getStock()) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Stock insuficiente para: " + item.getProducto().getNombre() +
                    "\nDisponibles: " + item.getProducto().getStock(),
                    "Stock insuficiente",
                    javax.swing.JOptionPane.ERROR_MESSAGE
                );
                return;
            }
        }
        
        // Confirmar compra
        double total = carritoManager.calcularTotal();
        int confirmar = javax.swing.JOptionPane.showConfirmDialog(
            this,
            String.format("Total a pagar: $%.2f\n¿Confirmar compra?", total),
            "Confirmar compra",
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        
        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
            // Descontar stock de cada producto
            for (modelo.entidades.ItemCarrito item : items) {
                modelo.entidades.Producto producto = item.getProducto();
                producto.setStock(producto.getStock() - item.getCantidad());
            }
            
            // Guardar productos actualizados
            productoManager.guardarProductosEnArchivo();
            
            // Agregar compra al historial
            panelTienda.registrarCompraEnHistorial(items, total);
            
            // Vaciar carrito
            carritoManager.vaciarCarrito();
            
            // Mostrar éxito
            javax.swing.JOptionPane.showMessageDialog(
                this,
                String.format("¡Compra realizada exitosamente!\n\nTotal pagado: $%.2f\nGracias por tu compra.", total),
                "Compra exitosa",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
            
            // Recargar carrito (mostrará vacío)
            cargarCarrito();
            
            // Preguntar si quiere ver el historial
            int verHistorial = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Deseas ver tu historial de compras?",
                "Ver historial",
                javax.swing.JOptionPane.YES_NO_OPTION
            );
            
            if (verHistorial == javax.swing.JOptionPane.YES_OPTION) {
            panelTienda.mostrarHistorial();
            }
        }
    }
    
    // ========== MÉTODOS AUXILIARES ==========
    
    private void actualizarTotal() {
        double total = carritoManager.calcularTotal();
        lblTotal.setText(String.format("Total: $%.2f", total));
    }
    
    private String obtenerEmojiPorCategoria(String categoria) {
        switch (categoria.toLowerCase()) {
            case "tecnologia":
            case "tecnología":
                return "📱";
            case "hogar":
                return "🏠";
            case "ropa":
                return "👕";
            case "alimentos":
                return "🍔";
            case "deportes":
                return "⚽";
            default:
                return "📦";
        }
    }
}
