/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author estra
 */
public class SubPanelCatalogo extends javax.swing.JPanel {
    
    // ========== ATRIBUTOS ==========
    private PanelTienda panelTienda;
    private modelo.gestores.ProductoManager productoManager;
    private modelo.gestores.CarritoManager carritoManager;
    private modelo.gestores.DeseosManager deseosManager;


    /**
     * Creates new form SubPanelCatalogo
     */
    public SubPanelCatalogo(PanelTienda panelTienda, modelo.gestores.ProductoManager productoManager,
                             modelo.gestores.CarritoManager carritoManager, modelo.gestores.DeseosManager deseosManager) {
        
        this.panelTienda = panelTienda;
        this.productoManager = productoManager;
        this.carritoManager = carritoManager;
        this.deseosManager = deseosManager;
        initComponents();
        
        // Configurar BoxLayout con eje Y (vertical)
        panelProductos.setLayout(new javax.swing.BoxLayout(panelProductos, javax.swing.BoxLayout.Y_AXIS));
        
        // Cargar productos
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        panelProductos = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 590));
        setLayout(new java.awt.BorderLayout());

        panelProductos.setBackground(new java.awt.Color(255, 255, 255));
        panelProductos.setLayout(new javax.swing.BoxLayout(panelProductos, javax.swing.BoxLayout.LINE_AXIS));
        scrollPane.setViewportView(panelProductos);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // ========== MÉTODOS PARA CARGAR Y MOSTRAR PRODUCTOS ==========
    
    private void cargarProductos() {
        java.util.List<modelo.entidades.Producto> productos = productoManager.obtenerTodosProductos();
        
        if (productos.isEmpty()) {
            javax.swing.JLabel lblVacio = new javax.swing.JLabel("No hay productos disponibles");
            lblVacio.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 16));
            lblVacio.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
            panelProductos.add(lblVacio);
        } else {
            for (modelo.entidades.Producto producto : productos) {
                panelProductos.add(crearTarjetaProducto(producto));
                panelProductos.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10))); // Espaciado
            }
        }
        
        panelProductos.revalidate();
        panelProductos.repaint();
    }
    
    private javax.swing.JPanel crearTarjetaProducto(modelo.entidades.Producto producto) {
        javax.swing.JPanel tarjeta = new javax.swing.JPanel();
        tarjeta.setLayout(new java.awt.BorderLayout(10, 10));
        tarjeta.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1),
            javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)
        ));
        tarjeta.setBackground(java.awt.Color.WHITE);
        tarjeta.setMaximumSize(new java.awt.Dimension(850, 200));
        
        // Panel izquierdo: Imagen
        javax.swing.JPanel panelImagen = crearPanelImagen(producto);
        tarjeta.add(panelImagen, java.awt.BorderLayout.WEST);
        
        // Panel central: Info del producto
        javax.swing.JPanel panelInfo = crearPanelInfo(producto);
        tarjeta.add(panelInfo, java.awt.BorderLayout.CENTER);
        
        // Panel derecho: Botones de acción
        javax.swing.JPanel panelAcciones = crearPanelAcciones(producto);
        tarjeta.add(panelAcciones, java.awt.BorderLayout.EAST);
        
        return tarjeta;
    }
    
    private javax.swing.JPanel crearPanelImagen(modelo.entidades.Producto producto) {
        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setLayout(new java.awt.BorderLayout());
        panel.setPreferredSize(new java.awt.Dimension(180, 170));
        panel.setBackground(java.awt.Color.WHITE);
        
        // Etiqueta para mostrar imagen (emoji como placeholder)
        javax.swing.JLabel lblImagen = new javax.swing.JLabel();
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 60));
        
        // Asignar emoji según categoría
        String emoji = obtenerEmojiPorCategoria(producto.getCategoria());
        lblImagen.setText(emoji);
        lblImagen.setOpaque(true);
        lblImagen.setBackground(new java.awt.Color(240, 240, 250));
        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1));
        lblImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        
        // Click en imagen para ver detalles
        lblImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarDetallesProducto(producto);
            }
        });
        
        panel.add(lblImagen, java.awt.BorderLayout.CENTER);
        
        // Botones de navegación de imágenes (si tiene múltiples)
        if (producto.getListaImagenes().getTamaño() > 1) {
            javax.swing.JPanel panelNavegacion = new javax.swing.JPanel(new java.awt.FlowLayout());
            panelNavegacion.setBackground(java.awt.Color.WHITE);
            
            javax.swing.JButton btnAnterior = new javax.swing.JButton("◄");
            btnAnterior.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 10));
            btnAnterior.addActionListener(e -> {
                producto.anteriorImagen();
                lblImagen.setText(obtenerEmojiPorCategoria(producto.getCategoria()));
            });
            
            javax.swing.JButton btnSiguiente = new javax.swing.JButton("►");
            btnSiguiente.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 10));
            btnSiguiente.addActionListener(e -> {
                producto.siguienteImagen();
                lblImagen.setText(obtenerEmojiPorCategoria(producto.getCategoria()));
            });
            
            panelNavegacion.add(btnAnterior);
            panelNavegacion.add(btnSiguiente);
            panel.add(panelNavegacion, java.awt.BorderLayout.SOUTH);
        }
        
        return panel;
    }
    
    private javax.swing.JPanel crearPanelInfo(modelo.entidades.Producto producto) {
        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.Y_AXIS));
        panel.setBackground(java.awt.Color.WHITE);
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        
        // Nombre (clickeable)
        javax.swing.JLabel lblNombre = new javax.swing.JLabel(producto.getNombre());
        lblNombre.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        lblNombre.setForeground(new java.awt.Color(50, 50, 50));
        lblNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarDetallesProducto(producto);
            }
        });
        
        // Precio
        javax.swing.JLabel lblPrecio = new javax.swing.JLabel(String.format("$%.2f", producto.getPrecio()));
        lblPrecio.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 20));
        lblPrecio.setForeground(new java.awt.Color(102, 126, 234));
        
        // Categoría
        javax.swing.JLabel lblCategoria = new javax.swing.JLabel("Categoría: " + producto.getCategoria());
        lblCategoria.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 12));
        lblCategoria.setForeground(new java.awt.Color(120, 120, 120));
        
        // Descripción (truncada)
        String descripcionCorta = producto.getDescripcion();
        if (descripcionCorta.length() > 80) {
            descripcionCorta = descripcionCorta.substring(0, 80) + "...";
        }
        javax.swing.JLabel lblDescripcion = new javax.swing.JLabel("<html>" + descripcionCorta + "</html>");
        lblDescripcion.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 13));
        lblDescripcion.setForeground(new java.awt.Color(80, 80, 80));
        
        // Stock
        javax.swing.JLabel lblStock = new javax.swing.JLabel("Stock: " + producto.getStock() + " unidades");
        lblStock.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 12));
        lblStock.setForeground(producto.getStock() > 5 ? new java.awt.Color(0, 150, 0) : new java.awt.Color(200, 0, 0));
        
        panel.add(lblNombre);
        panel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
        panel.add(lblPrecio);
        panel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
        panel.add(lblCategoria);
        panel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 8)));
        panel.add(lblDescripcion);
        panel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 8)));
        panel.add(lblStock);
        
        return panel;
    }
    
    private javax.swing.JPanel crearPanelAcciones(modelo.entidades.Producto producto) {
        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.Y_AXIS));
        panel.setBackground(java.awt.Color.WHITE);
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        // Botón Agregar al Carrito
        javax.swing.JButton btnCarrito = new javax.swing.JButton("🛒 Agregar al Carrito");
        btnCarrito.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
        btnCarrito.setBackground(new java.awt.Color(102, 126, 234));
        btnCarrito.setForeground(java.awt.Color.WHITE);
        btnCarrito.setFocusPainted(false);
        btnCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCarrito.setMaximumSize(new java.awt.Dimension(180, 35));
        btnCarrito.addActionListener(e -> agregarAlCarrito(producto));
        
        // Botón Agregar a Deseos
        javax.swing.JButton btnDeseos = new javax.swing.JButton("❤️ Agregar a Deseos");
        btnDeseos.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 12));
        btnDeseos.setBackground(new java.awt.Color(255, 140, 0));
        btnDeseos.setForeground(java.awt.Color.WHITE);
        btnDeseos.setFocusPainted(false);
        btnDeseos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeseos.setMaximumSize(new java.awt.Dimension(180, 35));
        btnDeseos.addActionListener(e -> agregarADeseos(producto));
        
        // Botón Ver Detalles
        javax.swing.JButton btnDetalles = new javax.swing.JButton("ℹ️ Ver Detalles");
        btnDetalles.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 11));
        btnDetalles.setBackground(new java.awt.Color(158, 158, 158));
        btnDetalles.setForeground(java.awt.Color.WHITE);
        btnDetalles.setFocusPainted(false);
        btnDetalles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDetalles.setMaximumSize(new java.awt.Dimension(180, 30));
        btnDetalles.addActionListener(e -> mostrarDetallesProducto(producto));
        
        panel.add(btnCarrito);
        panel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
        panel.add(btnDeseos);
        panel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
        panel.add(btnDetalles);
        panel.add(javax.swing.Box.createVerticalGlue());
        
        return panel;
    }
    
    // ========== MÉTODOS DE ACCIONES ==========
    
    private void agregarAlCarrito(modelo.entidades.Producto producto) {
        if (producto.getStock() <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Lo sentimos, este producto está agotado", 
                "Sin stock", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        carritoManager.agregarAlCarrito(producto, 1);
        javax.swing.JOptionPane.showMessageDialog(this, 
            producto.getNombre() + " agregado al carrito", 
            "Éxito", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void agregarADeseos(modelo.entidades.Producto producto) {
        deseosManager.agregarADeseos(producto);
        javax.swing.JOptionPane.showMessageDialog(this, 
            producto.getNombre() + " agregado a tu lista de deseos", 
            "Éxito", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void mostrarDetallesProducto(modelo.entidades.Producto producto) {
        // Crear diálogo con detalles completos
        javax.swing.JDialog dialogo = new javax.swing.JDialog((java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this), "Detalles del Producto", true);
        dialogo.setSize(600, 450);
        dialogo.setLocationRelativeTo(this);
        dialogo.setLayout(new java.awt.BorderLayout(15, 15));
        
        // Panel principal con padding
        javax.swing.JPanel panelPrincipal = new javax.swing.JPanel(new java.awt.BorderLayout(15, 15));
        panelPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelPrincipal.setBackground(java.awt.Color.WHITE);
        
        // Imagen grande
        javax.swing.JLabel lblImagenGrande = new javax.swing.JLabel();
        lblImagenGrande.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagenGrande.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 100));
        lblImagenGrande.setText(obtenerEmojiPorCategoria(producto.getCategoria()));
        lblImagenGrande.setOpaque(true);
        lblImagenGrande.setBackground(new java.awt.Color(240, 240, 250));
        lblImagenGrande.setPreferredSize(new java.awt.Dimension(200, 200));
        lblImagenGrande.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 2));
        
        // Información detallada
        javax.swing.JPanel panelInfo = new javax.swing.JPanel();
        panelInfo.setLayout(new javax.swing.BoxLayout(panelInfo, javax.swing.BoxLayout.Y_AXIS));
        panelInfo.setBackground(java.awt.Color.WHITE);
        
        javax.swing.JLabel lblNombreDetalle = new javax.swing.JLabel(producto.getNombre());
        lblNombreDetalle.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 22));
        
        javax.swing.JLabel lblPrecioDetalle = new javax.swing.JLabel(String.format("Precio: $%.2f", producto.getPrecio()));
        lblPrecioDetalle.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        lblPrecioDetalle.setForeground(new java.awt.Color(102, 126, 234));
        
        javax.swing.JLabel lblCategoriaDetalle = new javax.swing.JLabel("Categoría: " + producto.getCategoria());
        lblCategoriaDetalle.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 14));
        
        javax.swing.JLabel lblStockDetalle = new javax.swing.JLabel("Disponibles: " + producto.getStock() + " unidades");
        lblStockDetalle.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 14));
        
        javax.swing.JTextArea txtDescripcionDetalle = new javax.swing.JTextArea(producto.getDescripcion());
        txtDescripcionDetalle.setEditable(false);
        txtDescripcionDetalle.setLineWrap(true);
        txtDescripcionDetalle.setWrapStyleWord(true);
        txtDescripcionDetalle.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 13));
        txtDescripcionDetalle.setBackground(java.awt.Color.WHITE);
        javax.swing.JScrollPane scrollDescripcion = new javax.swing.JScrollPane(txtDescripcionDetalle);
        scrollDescripcion.setPreferredSize(new java.awt.Dimension(350, 100));
        
        panelInfo.add(lblNombreDetalle);
        panelInfo.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
        panelInfo.add(lblPrecioDetalle);
        panelInfo.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
        panelInfo.add(lblCategoriaDetalle);
        panelInfo.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
        panelInfo.add(lblStockDetalle);
        panelInfo.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 15)));
        panelInfo.add(new javax.swing.JLabel("Descripción:"));
        panelInfo.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
        panelInfo.add(scrollDescripcion);
        
        // Botón cerrar
        javax.swing.JButton btnCerrar = new javax.swing.JButton("Cerrar");
        btnCerrar.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
        btnCerrar.addActionListener(e -> dialogo.dispose());
        
        javax.swing.JPanel panelBoton = new javax.swing.JPanel();
        panelBoton.setBackground(java.awt.Color.WHITE);
        panelBoton.add(btnCerrar);
        
        panelPrincipal.add(lblImagenGrande, java.awt.BorderLayout.WEST);
        panelPrincipal.add(panelInfo, java.awt.BorderLayout.CENTER);
        panelPrincipal.add(panelBoton, java.awt.BorderLayout.SOUTH);
        
        dialogo.add(panelPrincipal);
        dialogo.setVisible(true);
    }
    
    private String obtenerEmojiPorCategoria(String categoria) {
        switch (categoria.toLowerCase()) {
            case "tecnologia":
            case "tecnología":
                return "📱";
            case "hogar":
                return "🏠";
            case "ropa":
                return "👕";
            case "alimentos":
                return "🍔";
            case "deportes":
                return "⚽";
            default:
                return "📦";
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelProductos;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
