/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import modelo.entidades.Producto;
import modelo.gestores.ProductoManager;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class SubPanelGestionProductos extends javax.swing.JPanel {
    
    private ProductoManager productoManager;
    private DefaultTableModel modeloTabla;
    private PanelAdmin panelAdmin;

    public SubPanelGestionProductos(PanelAdmin panelAdmin, ProductoManager productoManager) {
        this.panelAdmin = panelAdmin;
        this.productoManager = productoManager;
        initComponents();
        configurarTabla();
        cargarProductosEnTabla();
        configurarEventos();
    }
    
    private void configurarTabla() {
        String[] columnas = {"ID", "Nombre", "Precio", "Stock", "Categoría"};
        modeloTabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tablaProductos.setModel(modeloTabla);
        tablaProductos.setAutoCreateRowSorter(true);
        tablaProductos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tablaProductos.setRowHeight(25);
        
        tablaProductos.getColumnModel().getColumn(0).setPreferredWidth(50);
        tablaProductos.getColumnModel().getColumn(1).setPreferredWidth(200);
        tablaProductos.getColumnModel().getColumn(2).setPreferredWidth(80);
        tablaProductos.getColumnModel().getColumn(3).setPreferredWidth(60);
        tablaProductos.getColumnModel().getColumn(4).setPreferredWidth(100);
    }
    
    private void cargarProductosEnTabla() {
        modeloTabla.setRowCount(0);
        
        for (Producto producto : productoManager.obtenerTodosProductos()) {
            Object[] fila = {
                producto.getId(),
                producto.getNombre(),
                String.format("$%.2f", producto.getPrecio()),
                producto.getStock(),
                producto.getCategoria()
            };
            modeloTabla.addRow(fila);
        }
    }
    
    private void configurarEventos() {
        tablaProductos.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                cargarProductoSeleccionado();
            }
        });
    }
    
    private void cargarProductoSeleccionado() {
        int filaSeleccionada = tablaProductos.getSelectedRow();
        if (filaSeleccionada >= 0) {
            int id = Integer.parseInt(modeloTabla.getValueAt(filaSeleccionada, 0).toString());
            Producto producto = productoManager.obtenerProducto(id);
        
            if (producto != null) {
                txtId.setText(String.valueOf(producto.getId()));
                txtNombre.setText(producto.getNombre());
                txtPrecio.setText(String.valueOf(producto.getPrecio()));
                txtStock.setText(String.valueOf(producto.getStock()));
                cbCategoria.setSelectedItem(producto.getCategoria());
                txtDescripcion.setText(producto.getDescripcion());
            
                // Mostrar todas las imágenes separadas por punto y coma
                if (!producto.getListaImagenes().estaVacia()) {
                    java.util.List<String> imagenes = producto.getListaImagenes().obtenerTodas();
                    txtImagen.setText(String.join(";", imagenes));
                } else {
                    txtImagen.setText("");
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField1 = new javax.swing.JTextField();
        panelSuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelCentral = new javax.swing.JPanel();
        panelFormulario = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        lblDescripcion = new javax.swing.JLabel();
        scrollTabla0 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblImagen = new javax.swing.JLabel();
        txtImagen = new javax.swing.JTextField();
        panelBotones = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        scrollTabla = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();

        jTextField1.setText("jTextField1");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 590));
        setLayout(new java.awt.BorderLayout());

        panelSuperior.setBackground(new java.awt.Color(220, 53, 69));
        panelSuperior.setPreferredSize(new java.awt.Dimension(900, 60));
        panelSuperior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 10));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Gestión de Productos");
        panelSuperior.add(lblTitulo);

        add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelCentral.setBackground(new java.awt.Color(255, 255, 255));
        panelCentral.setLayout(new java.awt.BorderLayout());

        panelFormulario.setBackground(new java.awt.Color(236, 240, 241));
        panelFormulario.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        panelFormulario.setPreferredSize(new java.awt.Dimension(900, 280));
        panelFormulario.setLayout(new java.awt.GridBagLayout());

        lblId.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblId.setText("ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        panelFormulario.add(lblId, gridBagConstraints);

        txtId.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        panelFormulario.add(txtId, gridBagConstraints);

        lblNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        panelFormulario.add(lblNombre, gridBagConstraints);

        txtNombre.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        panelFormulario.add(txtNombre, gridBagConstraints);

        lblPrecio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPrecio.setText("Precio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        panelFormulario.add(lblPrecio, gridBagConstraints);

        txtPrecio.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        panelFormulario.add(txtPrecio, gridBagConstraints);

        lblStock.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblStock.setText("Stock:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        panelFormulario.add(lblStock, gridBagConstraints);

        txtStock.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        panelFormulario.add(txtStock, gridBagConstraints);

        lblCategoria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCategoria.setText("Categoria:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        panelFormulario.add(lblCategoria, gridBagConstraints);

        cbCategoria.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ropa", "Zapatos" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        panelFormulario.add(cbCategoria, gridBagConstraints);

        lblDescripcion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDescripcion.setText("Descripcion:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        panelFormulario.add(lblDescripcion, gridBagConstraints);

        txtDescripcion.setColumns(20);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(3);
        txtDescripcion.setWrapStyleWord(true);
        txtDescripcion.setPreferredSize(new java.awt.Dimension(230, 50));
        scrollTabla0.setViewportView(txtDescripcion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        panelFormulario.add(scrollTabla0, gridBagConstraints);

        lblImagen.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblImagen.setText("URLs Imagenes (separadas por ;): ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 10);
        panelFormulario.add(lblImagen, gridBagConstraints);

        txtImagen.setColumns(20);
        txtImagen.setToolTipText("Separa multiples imagenes con punto y coma (;) ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        panelFormulario.add(txtImagen, gridBagConstraints);

        panelCentral.add(panelFormulario, java.awt.BorderLayout.PAGE_START);

        panelBotones.setBackground(new java.awt.Color(255, 255, 255));
        panelBotones.setPreferredSize(new java.awt.Dimension(900, 60));
        panelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        btnAgregar.setBackground(new java.awt.Color(39, 174, 96));
        btnAgregar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar Producto");
        btnAgregar.setPreferredSize(new java.awt.Dimension(180, 40));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelBotones.add(btnAgregar);

        btnEditar.setBackground(new java.awt.Color(243, 156, 18));
        btnEditar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar Producto");
        btnEditar.setPreferredSize(new java.awt.Dimension(180, 40));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panelBotones.add(btnEditar);

        btnEliminar.setBackground(new java.awt.Color(231, 76, 60));
        btnEliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar Producto");
        btnEliminar.setPreferredSize(new java.awt.Dimension(180, 40));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelBotones.add(btnEliminar);

        btnLimpiar.setBackground(new java.awt.Color(149, 165, 166));
        btnLimpiar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setPreferredSize(new java.awt.Dimension(180, 40));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panelBotones.add(btnLimpiar);

        panelCentral.add(panelBotones, java.awt.BorderLayout.PAGE_END);

        scrollTabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProductos.setPreferredSize(new java.awt.Dimension(300, 60));
        tablaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollTabla.setViewportView(tablaProductos);

        panelCentral.add(scrollTabla, java.awt.BorderLayout.CENTER);

        add(panelCentral, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (txtId.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Selecciona un producto de la tabla para editar.", 
                "Advertencia", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
    
        if (!validarCampos()) {
            return;
        }
    
        try {
            int id = Integer.parseInt(txtId.getText().trim());
            Producto productoExistente = productoManager.obtenerProducto(id);
        
            if (productoExistente != null) {
                double precio = Double.parseDouble(txtPrecio.getText().trim());
                int stock = Integer.parseInt(txtStock.getText().trim());
                String urlsImagenes = txtImagen.getText().trim();
            
                productoExistente.setPrecio(precio);
                productoExistente.setStock(stock);
            
                // Limpiar y agregar nuevas imágenes si se proporcionaron
                if (!urlsImagenes.isEmpty()) {
                    // Limpiar imágenes existentes
                    while (!productoExistente.getListaImagenes().estaVacia()) {
                        productoExistente.getListaImagenes().eliminarImagen(0);
                    }
                
                    // Agregar múltiples imágenes separadas por punto y coma
                    String[] imagenes = urlsImagenes.split(";");
                    for (String urlImagen : imagenes) {
                        String urlLimpia = urlImagen.trim();
                        if (!urlLimpia.isEmpty()) {
                            productoExistente.agregarImagen(urlLimpia);
                        }
                    }
                }
            
                productoManager.guardarProductosEnArchivo();
                cargarProductosEnTabla();
                limpiarCampos();
            
                JOptionPane.showMessageDialog(this, 
                    "Producto editado exitosamente!\n(Solo se pueden editar Precio, Stock e Imagenes)", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);
            }
        
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, 
                "Error en formato de números. Verifica Precio y Stock.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (!validarCampos()) {
            return;
        }
    
        try {
            int nuevoId = generarNuevoId();
        
            String nombre = txtNombre.getText().trim();
            double precio = Double.parseDouble(txtPrecio.getText().trim());
            int stock = Integer.parseInt(txtStock.getText().trim());
            String categoria = cbCategoria.getSelectedItem().toString();
            String descripcion = txtDescripcion.getText().trim();
            String urlsImagenes = txtImagen.getText().trim();
        
            Producto nuevoProducto = new Producto(nuevoId, nombre, precio, descripcion, stock, categoria);
        
            // Agregar múltiples imágenes separadas por punto y coma
            if (!urlsImagenes.isEmpty()) {
                String[] imagenes = urlsImagenes.split(";");
                for (String urlImagen : imagenes) {
                    String urlLimpia = urlImagen.trim();
                    if (!urlLimpia.isEmpty()) {
                        nuevoProducto.agregarImagen(urlLimpia);
                    }
                }
            }
        
            productoManager.agregarProducto(nuevoProducto);
            cargarProductosEnTabla();
            limpiarCampos();
        
            JOptionPane.showMessageDialog(this, 
                "Producto agregado exitosamente!", 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);
        
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, 
                "Error en formato de números. Verifica Precio y Stock.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (txtId.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Selecciona un producto de la tabla para eliminar.", 
                "Advertencia", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Estás seguro de eliminar este producto?\nEsta acción no se puede deshacer.", 
            "Confirmar Eliminación", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        
        if (confirmacion == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(txtId.getText().trim());
            if (productoManager.eliminarProducto(id)) {
                cargarProductosEnTabla();
                limpiarCampos();
                
                JOptionPane.showMessageDialog(this, 
                    "Producto eliminado exitosamente!", 
                    "Éxito", 
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, 
                    "No se pudo eliminar el producto.", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }
    
    private void limpiarCampos() {
        txtId.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
        cbCategoria.setSelectedIndex(0);
        txtDescripcion.setText("");
        txtImagen.setText("");
        tablaProductos.clearSelection();
    }
    
    private int generarNuevoId() {
        int maxId = 0;
        for (Producto producto : productoManager.obtenerTodosProductos()) {
            if (producto.getId() > maxId) {
                maxId = producto.getId();
            }
        }
        return maxId + 1;
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private boolean validarCampos() {
        if (txtNombre.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "El nombre del producto es obligatorio.", 
                "Campo Vacío", 
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        if (txtPrecio.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "El precio es obligatorio.", 
                "Campo Vacío", 
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        if (txtStock.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "El stock es obligatorio.", 
                "Campo Vacío", 
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        try {
            double precio = Double.parseDouble(txtPrecio.getText().trim());
            if (precio < 0) {
                JOptionPane.showMessageDialog(this, 
                    "El precio no puede ser negativo.", 
                    "Valor Inválido", 
                    JOptionPane.WARNING_MESSAGE);
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "El precio debe ser un número válido.", 
                "Formato Incorrecto", 
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        try {
            int stock = Integer.parseInt(txtStock.getText().trim());
            if (stock < 0) {
                JOptionPane.showMessageDialog(this, 
                    "El stock no puede ser negativo.", 
                    "Valor Inválido", 
                    JOptionPane.WARNING_MESSAGE);
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "El stock debe ser un número entero válido.", 
                "Formato Incorrecto", 
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JScrollPane scrollTabla0;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtImagen;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
