/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author estra
 */
public class SubPanelEstadisticas extends javax.swing.JPanel {
    
    // ========== ATRIBUTOS ==========
    private PanelAdmin panelAdmin;
    private modelo.gestores.UsuarioManager usuarioManager; 
    private modelo.gestores.ProductoManager productoManager;

    /**
     * Creates new form SubPanelEstadisticas
     */
    public SubPanelEstadisticas(PanelAdmin panelAdmin, 
                             modelo.gestores.UsuarioManager usuarioManager,
                             modelo.gestores.ProductoManager productoManager) {
        this.panelAdmin = panelAdmin;
        this.usuarioManager = usuarioManager;
        this.productoManager = productoManager;
      
        initComponents();
    
        // Configurar BoxLayout para panelContenido (vertical)
        panelContenido.setLayout(new javax.swing.BoxLayout(panelContenido, javax.swing.BoxLayout.Y_AXIS));
    
        // Cargar estadísticas
        cargarEstadisticas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        panelContenido = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 590));
        setLayout(new java.awt.BorderLayout());

        panelSuperior.setBackground(new java.awt.Color(220, 53, 69));
        panelSuperior.setPreferredSize(new java.awt.Dimension(900, 60));
        panelSuperior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 10));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Estadisticas del Negocio");
        panelSuperior.add(lblTitulo);

        add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelContenido.setBackground(new java.awt.Color(245, 245, 245));
        panelContenido.setLayout(new javax.swing.BoxLayout(panelContenido, javax.swing.BoxLayout.Y_AXIS));
        scrollPane.setViewportView(panelContenido);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // ========== MÉTODOS ==========

private void cargarEstadisticas() {
    panelContenido.removeAll();
    
    // Agregar espaciado inicial
    panelContenido.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 20)));
    
    // 1. Estadísticas Generales
    panelContenido.add(crearSeccionEstadisticasGenerales());
    panelContenido.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 20)));
    
    // 2. Productos Más Vendidos
    panelContenido.add(crearSeccionProductosMasVendidos());
    panelContenido.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 20)));
    
    // 3. Categorías Más Populares
    panelContenido.add(crearSeccionCategorias());
    panelContenido.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 20)));
    
    // 4. Inventario Bajo Stock
    panelContenido.add(crearSeccionInventario());
    panelContenido.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 20)));
    
    panelContenido.revalidate();
    panelContenido.repaint();
}

private javax.swing.JPanel crearSeccionEstadisticasGenerales() {
    javax.swing.JPanel panel = crearPanelSeccion("Estadisticas Generales");
    
    // Calcular estadísticas
    EstadisticasGenerales stats = calcularEstadisticasGenerales();
    
    // Grid para mostrar las estadísticas
    javax.swing.JPanel gridPanel = new javax.swing.JPanel(new java.awt.GridLayout(2, 3, 20, 15));
    gridPanel.setBackground(java.awt.Color.WHITE);
    gridPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
    
    // Tarjetas de estadísticas
    gridPanel.add(crearTarjetaEstadistica("Total Ventas", String.format("$%.2f", stats.totalVentas), 
                                          new java.awt.Color(39, 174, 96)));
    gridPanel.add(crearTarjetaEstadistica("Total Compras", String.valueOf(stats.totalCompras), 
                                          new java.awt.Color(52, 152, 219)));
    gridPanel.add(crearTarjetaEstadistica("Productos Vendidos", String.valueOf(stats.totalProductosVendidos), 
                                          new java.awt.Color(155, 89, 182)));
    gridPanel.add(crearTarjetaEstadistica("Total Usuarios", String.valueOf(stats.totalUsuarios), 
                                          new java.awt.Color(230, 126, 34)));
    gridPanel.add(crearTarjetaEstadistica("Productos en Catalogo", String.valueOf(stats.totalProductosCatalogo), 
                                          new java.awt.Color(241, 196, 15)));
    gridPanel.add(crearTarjetaEstadistica("Promedio por Compra", String.format("$%.2f", stats.promedioCompra), 
                                          new java.awt.Color(231, 76, 60)));
    
    panel.add(gridPanel, java.awt.BorderLayout.CENTER);
    return panel;
}

private javax.swing.JPanel crearSeccionProductosMasVendidos() {
    javax.swing.JPanel panel = crearPanelSeccion("Top 5 Productos Mas Vendidos");
    
    java.util.List<ProductoVendido> topProductos = calcularProductosMasVendidos();
    
    if (topProductos.isEmpty()) {
        javax.swing.JLabel lblVacio = new javax.swing.JLabel("No hay productos vendidos aun");
        lblVacio.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 14));
        lblVacio.setForeground(new java.awt.Color(150, 150, 150));
        lblVacio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(lblVacio, java.awt.BorderLayout.CENTER);
    } else {
        javax.swing.JPanel listaPanel = new javax.swing.JPanel();
        listaPanel.setLayout(new javax.swing.BoxLayout(listaPanel, javax.swing.BoxLayout.Y_AXIS));
        listaPanel.setBackground(java.awt.Color.WHITE);
        listaPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        
        int posicion = 1;
        for (ProductoVendido pv : topProductos) {
            listaPanel.add(crearItemProductoVendido(posicion, pv));
            if (posicion < topProductos.size()) {
                listaPanel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
            }
            posicion++;
        }
        
        panel.add(listaPanel, java.awt.BorderLayout.CENTER);
    }
    
    return panel;
}

private javax.swing.JPanel crearSeccionCategorias() {
    javax.swing.JPanel panel = crearPanelSeccion("Ventas por Categoria");
    
    java.util.Map<String, Integer> ventasPorCategoria = calcularVentasPorCategoria();
    
    if (ventasPorCategoria.isEmpty()) {
        javax.swing.JLabel lblVacio = new javax.swing.JLabel("No hay ventas por categoria");
        lblVacio.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 14));
        lblVacio.setForeground(new java.awt.Color(150, 150, 150));
        lblVacio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(lblVacio, java.awt.BorderLayout.CENTER);
    } else {
        javax.swing.JPanel listaPanel = new javax.swing.JPanel();
        listaPanel.setLayout(new javax.swing.BoxLayout(listaPanel, javax.swing.BoxLayout.Y_AXIS));
        listaPanel.setBackground(java.awt.Color.WHITE);
        listaPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        
        for (java.util.Map.Entry<String, Integer> entry : ventasPorCategoria.entrySet()) {
            listaPanel.add(crearItemCategoria(entry.getKey(), entry.getValue()));
            listaPanel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
        }
        
        panel.add(listaPanel, java.awt.BorderLayout.CENTER);
    }
    
    return panel;
}

private javax.swing.JPanel crearSeccionInventario() {
    javax.swing.JPanel panel = crearPanelSeccion("Alerta de Inventario (Stock < 5)");
    
    java.util.List<modelo.entidades.Producto> productosPocoStock = new java.util.ArrayList<>();
    
    for (modelo.entidades.Producto producto : productoManager.obtenerTodosProductos()) {
        if (producto.getStock() < 5) {
            productosPocoStock.add(producto);
        }
    }
    
    if (productosPocoStock.isEmpty()) {
        javax.swing.JLabel lblVacio = new javax.swing.JLabel("Todos los productos tienen stock suficiente");
        lblVacio.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 14));
        lblVacio.setForeground(new java.awt.Color(39, 174, 96));
        lblVacio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel.add(lblVacio, java.awt.BorderLayout.CENTER);
    } else {
        javax.swing.JPanel listaPanel = new javax.swing.JPanel();
        listaPanel.setLayout(new javax.swing.BoxLayout(listaPanel, javax.swing.BoxLayout.Y_AXIS));
        listaPanel.setBackground(java.awt.Color.WHITE);
        listaPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 15, 20));
        
        for (modelo.entidades.Producto producto : productosPocoStock) {
            listaPanel.add(crearItemInventario(producto));
            listaPanel.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
        }
        
        panel.add(listaPanel, java.awt.BorderLayout.CENTER);
    }
    
    return panel;
}

// ========== MÉTODOS AUXILIARES ==========

private javax.swing.JPanel crearPanelSeccion(String titulo) {
    javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.BorderLayout());
    panel.setBackground(java.awt.Color.WHITE);
    panel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 2),
        javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0)
    ));
    panel.setMaximumSize(new java.awt.Dimension(850, Integer.MAX_VALUE));
    panel.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
    
    // Header
    javax.swing.JPanel headerPanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
    headerPanel.setBackground(new java.awt.Color(236, 240, 241));
    headerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15));
    
    javax.swing.JLabel lblTituloSeccion = new javax.swing.JLabel(titulo);
    lblTituloSeccion.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
    lblTituloSeccion.setForeground(new java.awt.Color(52, 73, 94));
    
    headerPanel.add(lblTituloSeccion);
    panel.add(headerPanel, java.awt.BorderLayout.NORTH);
    
    return panel;
}

private javax.swing.JPanel crearTarjetaEstadistica(String titulo, String valor, java.awt.Color color) {
    javax.swing.JPanel tarjeta = new javax.swing.JPanel();
    tarjeta.setLayout(new javax.swing.BoxLayout(tarjeta, javax.swing.BoxLayout.Y_AXIS));
    tarjeta.setBackground(color);
    tarjeta.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(color.darker(), 1),
        javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)
    ));
    
    javax.swing.JLabel lblValor = new javax.swing.JLabel(valor);
    lblValor.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 28));
    lblValor.setForeground(java.awt.Color.WHITE);
    lblValor.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
    
    javax.swing.JLabel lblTitulo = new javax.swing.JLabel(titulo);
    lblTitulo.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 13));
    lblTitulo.setForeground(java.awt.Color.WHITE);
    lblTitulo.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
    
    tarjeta.add(lblValor);
    tarjeta.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
    tarjeta.add(lblTitulo);
    
    return tarjeta;
}

private javax.swing.JPanel crearItemProductoVendido(int posicion, ProductoVendido pv) {
    javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.BorderLayout(10, 0));
    panel.setBackground(new java.awt.Color(250, 250, 250));
    panel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220), 1),
        javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15)
    ));
    panel.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 60));
    
    // Posición
    javax.swing.JLabel lblPosicion = new javax.swing.JLabel("#" + posicion);
    lblPosicion.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
    lblPosicion.setForeground(new java.awt.Color(52, 152, 219));
    lblPosicion.setPreferredSize(new java.awt.Dimension(50, 40));
    lblPosicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    
    // Info del producto
    javax.swing.JPanel panelInfo = new javax.swing.JPanel();
    panelInfo.setLayout(new javax.swing.BoxLayout(panelInfo, javax.swing.BoxLayout.Y_AXIS));
    panelInfo.setBackground(new java.awt.Color(250, 250, 250));
    
    javax.swing.JLabel lblNombre = new javax.swing.JLabel(pv.nombre);
    lblNombre.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
    
    javax.swing.JLabel lblInfo = new javax.swing.JLabel(
        String.format("Categoria: %s | Precio: $%.2f", pv.categoria, pv.precio)
    );
    lblInfo.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 12));
    lblInfo.setForeground(new java.awt.Color(100, 100, 100));
    
    panelInfo.add(lblNombre);
    panelInfo.add(lblInfo);
    
    // Cantidad vendida
    javax.swing.JLabel lblCantidad = new javax.swing.JLabel(pv.cantidadVendida + " vendidos");
    lblCantidad.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
    lblCantidad.setForeground(new java.awt.Color(39, 174, 96));
    
    panel.add(lblPosicion, java.awt.BorderLayout.WEST);
    panel.add(panelInfo, java.awt.BorderLayout.CENTER);
    panel.add(lblCantidad, java.awt.BorderLayout.EAST);
    
    return panel;
}

private javax.swing.JPanel crearItemCategoria(String categoria, int cantidad) {
    javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.BorderLayout(10, 0));
    panel.setBackground(new java.awt.Color(250, 250, 250));
    panel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220), 1),
        javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)
    ));
    panel.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 50));
    
    javax.swing.JLabel lblCategoria = new javax.swing.JLabel(categoria);
    lblCategoria.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
    lblCategoria.setForeground(new java.awt.Color(52, 73, 94));
    
    javax.swing.JLabel lblCantidad = new javax.swing.JLabel(cantidad + " unidades vendidas");
    lblCantidad.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
    lblCantidad.setForeground(new java.awt.Color(155, 89, 182));
    
    panel.add(lblCategoria, java.awt.BorderLayout.WEST);
    panel.add(lblCantidad, java.awt.BorderLayout.EAST);
    
    return panel;
}

private javax.swing.JPanel crearItemInventario(modelo.entidades.Producto producto) {
    javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.BorderLayout(10, 0));
    panel.setBackground(new java.awt.Color(255, 245, 245));
    panel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(231, 76, 60), 2),
        javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15)
    ));
    panel.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 50));
    
    javax.swing.JLabel lblNombre = new javax.swing.JLabel(producto.getNombre());
    lblNombre.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
    lblNombre.setForeground(new java.awt.Color(52, 73, 94));
    
    javax.swing.JLabel lblStock = new javax.swing.JLabel("Stock: " + producto.getStock() + " unidades");
    lblStock.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
    lblStock.setForeground(new java.awt.Color(231, 76, 60));
    
    panel.add(lblNombre, java.awt.BorderLayout.WEST);
    panel.add(lblStock, java.awt.BorderLayout.EAST);
    
    return panel;
}

// ========== CÁLCULOS DE ESTADÍSTICAS ==========

private EstadisticasGenerales calcularEstadisticasGenerales() {
    EstadisticasGenerales stats = new EstadisticasGenerales();
    
    // Total usuarios (excluyendo admin)
    for (modelo.entidades.Usuario usuario : usuarioManager.obtenerTodosUsuarios()) {
        if (!usuario.esAdministrador()) {
            stats.totalUsuarios++;
        }
    }
    
    // Total productos en catálogo
    stats.totalProductosCatalogo = productoManager.obtenerTodosProductos().size();
    
    // Recorrer todas las compras
    for (modelo.entidades.Usuario usuario : usuarioManager.obtenerTodosUsuarios()) {
        if (!usuario.esAdministrador()) {
            modelo.gestores.HistorialManager historialManager = 
                new modelo.gestores.HistorialManager(usuario.getNombre(), productoManager);
            
            for (modelo.entidades.Compra compra : historialManager.obtenerHistorial()) {
                stats.totalCompras++;
                stats.totalVentas += compra.getTotal();
                
                for (modelo.entidades.ItemCarrito item : compra.getProductos()) {
                    stats.totalProductosVendidos += item.getCantidad();
                }
            }
        }
    }
    
    // Promedio por compra
    if (stats.totalCompras > 0) {
        stats.promedioCompra = stats.totalVentas / stats.totalCompras;
    }
    
    return stats;
}

private java.util.List<ProductoVendido> calcularProductosMasVendidos() {
    java.util.Map<Integer, ProductoVendido> ventasPorProducto = new java.util.HashMap<>();
    
    // Recorrer todas las compras
    for (modelo.entidades.Usuario usuario : usuarioManager.obtenerTodosUsuarios()) {
        if (!usuario.esAdministrador()) {
            modelo.gestores.HistorialManager historialManager = 
                new modelo.gestores.HistorialManager(usuario.getNombre(), productoManager);
            
            for (modelo.entidades.Compra compra : historialManager.obtenerHistorial()) {
                for (modelo.entidades.ItemCarrito item : compra.getProductos()) {
                    modelo.entidades.Producto producto = item.getProducto();
                    int idProducto = producto.getId();
                    
                    if (!ventasPorProducto.containsKey(idProducto)) {
                        ventasPorProducto.put(idProducto, new ProductoVendido(
                            producto.getNombre(),
                            producto.getCategoria(),
                            producto.getPrecio(),
                            0
                        ));
                    }
                    
                    ProductoVendido pv = ventasPorProducto.get(idProducto);
                    pv.cantidadVendida += item.getCantidad();
                }
            }
        }
    }
    
    // Convertir a lista y ordenar
    java.util.List<ProductoVendido> lista = new java.util.ArrayList<>(ventasPorProducto.values());
    lista.sort((a, b) -> Integer.compare(b.cantidadVendida, a.cantidadVendida));
    
    // Retornar top 5
    return lista.size() > 5 ? lista.subList(0, 5) : lista;
}

private java.util.Map<String, Integer> calcularVentasPorCategoria() {
    java.util.Map<String, Integer> ventasPorCategoria = new java.util.HashMap<>();
    
    // Recorrer todas las compras
    for (modelo.entidades.Usuario usuario : usuarioManager.obtenerTodosUsuarios()) {
        if (!usuario.esAdministrador()) {
            modelo.gestores.HistorialManager historialManager = 
                new modelo.gestores.HistorialManager(usuario.getNombre(), productoManager);
            
            for (modelo.entidades.Compra compra : historialManager.obtenerHistorial()) {
                for (modelo.entidades.ItemCarrito item : compra.getProductos()) {
                    String categoria = item.getProducto().getCategoria();
                    ventasPorCategoria.put(categoria, 
                        ventasPorCategoria.getOrDefault(categoria, 0) + item.getCantidad());
                }
            }
        }
    }
    
    return ventasPorCategoria;
}

// ========== CLASES AUXILIARES ==========

private class EstadisticasGenerales {
    double totalVentas = 0.0;
    int totalCompras = 0;
    int totalProductosVendidos = 0;
    int totalUsuarios = 0;
    int totalProductosCatalogo = 0;
    double promedioCompra = 0.0;
}

private class ProductoVendido {
    String nombre;
    String categoria;
    double precio;
    int cantidadVendida;
    
    ProductoVendido(String nombre, String categoria, double precio, int cantidadVendida) {
        this.nombre = nombre;
        this.categoria = categoria;
        this.precio = precio;
        this.cantidadVendida = cantidadVendida;
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
