/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author estra
 */
public class SubPanelHistorial extends javax.swing.JPanel {
    
    // ========== ATRIBUTOS ==========
    private PanelTienda panelTienda;
    private modelo.gestores.HistorialManager historialManager;

    /**
     * Creates new form SubPanelHistorial
     */
    public SubPanelHistorial(PanelTienda panelTienda, modelo.gestores.HistorialManager historialManager) {
        
        this.panelTienda = panelTienda;
        this.historialManager = historialManager;
        
        initComponents();
        
        // Configurar BoxLayout para panelHistorial (vertical)
        panelHistorial.setLayout(new javax.swing.BoxLayout(panelHistorial, javax.swing.BoxLayout.Y_AXIS));
        
        // Cargar historial de compras
        cargarHistorial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        panelHistorial = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 590));
        setLayout(new java.awt.BorderLayout());

        panelHistorial.setBackground(new java.awt.Color(245, 245, 245));
        scrollPane.setViewportView(panelHistorial);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelHistorial;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
    // ========== MÉTODOS PARA CARGAR Y MOSTRAR HISTORIAL ==========
    
    private void cargarHistorial() {
        // Limpiar panel
        panelHistorial.removeAll();
        
        java.util.List<modelo.entidades.Compra> compras = historialManager.obtenerHistorial();
        
        if (compras.isEmpty()) {
            // Mostrar mensaje de historial vacío
            javax.swing.JLabel lblVacio = new javax.swing.JLabel("No has realizado compras aún");
            lblVacio.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            lblVacio.setForeground(new java.awt.Color(150, 150, 150));
            lblVacio.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
            
            javax.swing.JLabel lblEmoji = new javax.swing.JLabel("📜");
            lblEmoji.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 80));
            lblEmoji.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
            
            javax.swing.JLabel lblMensaje = new javax.swing.JLabel("Tu historial de compras aparecerá aquí");
            lblMensaje.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 14));
            lblMensaje.setForeground(new java.awt.Color(120, 120, 120));
            lblMensaje.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
            
            panelHistorial.add(javax.swing.Box.createVerticalGlue());
            panelHistorial.add(lblEmoji);
            panelHistorial.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 20)));
            panelHistorial.add(lblVacio);
            panelHistorial.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
            panelHistorial.add(lblMensaje);
            panelHistorial.add(javax.swing.Box.createVerticalGlue());
        } else {
            // Agregar espaciado inicial
            panelHistorial.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 15)));
            
            // Crear tarjetas para cada compra (de más reciente a más antigua)
            // Las compras en la cola están en orden cronológico (FIFO)
            // Mostramos en orden inverso para ver las más recientes primero
            for (int i = compras.size() - 1; i >= 0; i--) {
                panelHistorial.add(crearTarjetaCompra(compras.get(i), compras.size() - i));
                panelHistorial.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 15)));
            }
        }
        
        panelHistorial.revalidate();
        panelHistorial.repaint();
    }
    
    private javax.swing.JPanel crearTarjetaCompra(modelo.entidades.Compra compra, int numeroCompra) {
        javax.swing.JPanel tarjeta = new javax.swing.JPanel();
        tarjeta.setLayout(new javax.swing.BoxLayout(tarjeta, javax.swing.BoxLayout.Y_AXIS));
        tarjeta.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 2),
            javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)
        ));
        tarjeta.setBackground(java.awt.Color.WHITE);
        tarjeta.setMaximumSize(new java.awt.Dimension(850, Integer.MAX_VALUE));
        
        // ========== ENCABEZADO DE LA COMPRA ==========
        
        // Panel de encabezado
        javax.swing.JPanel panelEncabezado = new javax.swing.JPanel();
        panelEncabezado.setLayout(new java.awt.BorderLayout());
        panelEncabezado.setBackground(java.awt.Color.WHITE);
        panelEncabezado.setAlignmentX(javax.swing.JComponent.LEFT_ALIGNMENT);
        
        // Label de fecha y número
        javax.swing.JLabel lblFecha = new javax.swing.JLabel(
            String.format("📅 Compra #%d - %s", numeroCompra, formatearFecha(compra.getFecha()))
        );
        lblFecha.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        lblFecha.setForeground(new java.awt.Color(50, 50, 50));
        
        panelEncabezado.add(lblFecha, java.awt.BorderLayout.WEST);
        
        tarjeta.add(panelEncabezado);
        tarjeta.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
        
        // Separador
        javax.swing.JSeparator separador1 = new javax.swing.JSeparator();
        separador1.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 1));
        separador1.setForeground(new java.awt.Color(220, 220, 220));
        tarjeta.add(separador1);
        tarjeta.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 15)));
        
        // ========== PRODUCTOS DE LA COMPRA ==========
        
        java.util.List<modelo.entidades.ItemCarrito> productos = compra.getProductos();
        
        for (modelo.entidades.ItemCarrito item : productos) {
            javax.swing.JPanel panelProducto = crearPanelProductoHistorial(item);
            tarjeta.add(panelProducto);
            tarjeta.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 12)));
        }
        
        // ========== PIE DE LA COMPRA (TOTAL) ==========
        
        tarjeta.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
        
        // Separador
        javax.swing.JSeparator separador2 = new javax.swing.JSeparator();
        separador2.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 1));
        separador2.setForeground(new java.awt.Color(220, 220, 220));
        tarjeta.add(separador2);
        tarjeta.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 15)));
        
        // Panel de total
        javax.swing.JPanel panelTotal = new javax.swing.JPanel();
        panelTotal.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        panelTotal.setBackground(java.awt.Color.WHITE);
        panelTotal.setAlignmentX(javax.swing.JComponent.LEFT_ALIGNMENT);
        
        javax.swing.JLabel lblTotal = new javax.swing.JLabel(
            String.format("TOTAL PAGADO: $%.2f", compra.getTotal())
        );
        lblTotal.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        lblTotal.setForeground(new java.awt.Color(40, 167, 69));
        
        panelTotal.add(lblTotal);
        tarjeta.add(panelTotal);
        
        return tarjeta;
    }
    
    private javax.swing.JPanel crearPanelProductoHistorial(modelo.entidades.ItemCarrito item) {
        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setLayout(new java.awt.BorderLayout(10, 0));
        panel.setBackground(new java.awt.Color(250, 250, 250));
        panel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230), 1),
            javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15)
        ));
        panel.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 80));
        panel.setAlignmentX(javax.swing.JComponent.LEFT_ALIGNMENT);
        
        modelo.entidades.Producto producto = item.getProducto();
        
        // ========== IMAGEN (WEST) ==========
        
        javax.swing.JLabel lblImagen = new javax.swing.JLabel();
        lblImagen.setPreferredSize(new java.awt.Dimension(60, 60));
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setOpaque(true);
        lblImagen.setBackground(java.awt.Color.WHITE);
        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 1));
        
        // Cargar imagen o emoji
        try {
            String rutaImagen = producto.getImagenActual();
            java.io.File archivoImagen = new java.io.File(rutaImagen);
            
            if (archivoImagen.exists()) {
                javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(rutaImagen);
                java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(
                    55, 55, java.awt.Image.SCALE_SMOOTH
                );
                lblImagen.setIcon(new javax.swing.ImageIcon(imagenEscalada));
            } else {
                lblImagen.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 30));
                lblImagen.setText(obtenerEmojiPorCategoria(producto.getCategoria()));
            }
        } catch (Exception e) {
            lblImagen.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 30));
            lblImagen.setText(obtenerEmojiPorCategoria(producto.getCategoria()));
        }
        
        panel.add(lblImagen, java.awt.BorderLayout.WEST);
        
        // ========== INFORMACIÓN (CENTER) ==========
        
        javax.swing.JPanel panelInfo = new javax.swing.JPanel();
        panelInfo.setLayout(new javax.swing.BoxLayout(panelInfo, javax.swing.BoxLayout.Y_AXIS));
        panelInfo.setBackground(new java.awt.Color(250, 250, 250));
        
        // Nombre
        javax.swing.JLabel lblNombre = new javax.swing.JLabel(producto.getNombre());
        lblNombre.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
        lblNombre.setAlignmentX(javax.swing.JComponent.LEFT_ALIGNMENT);
        
        // Cantidad y precio unitario
        javax.swing.JLabel lblCantidadPrecio = new javax.swing.JLabel(
            String.format("Cantidad: %d × $%.2f", item.getCantidad(), producto.getPrecio())
        );
        lblCantidadPrecio.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 12));
        lblCantidadPrecio.setForeground(new java.awt.Color(100, 100, 100));
        lblCantidadPrecio.setAlignmentX(javax.swing.JComponent.LEFT_ALIGNMENT);
        
        panelInfo.add(lblNombre);
        panelInfo.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
        panelInfo.add(lblCantidadPrecio);
        
        panel.add(panelInfo, java.awt.BorderLayout.CENTER);
        
        // ========== SUBTOTAL (EAST) ==========
        
        javax.swing.JLabel lblSubtotal = new javax.swing.JLabel(
            String.format("$%.2f", item.getSubtotal())
        );
        lblSubtotal.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        lblSubtotal.setForeground(new java.awt.Color(102, 126, 234));
        
        panel.add(lblSubtotal, java.awt.BorderLayout.EAST);
        
        return panel;
    }
    
    // ========== MÉTODOS AUXILIARES ==========
    
    private String formatearFecha(String fecha) {
        // La fecha viene en formato: yyyy-MM-dd
        // La convertimos a formato más legible: dd/MM/yyyy
        try {
            String[] partes = fecha.split("-");
            if (partes.length == 3) {
                return partes[2] + "/" + partes[1] + "/" + partes[0];
            }
        } catch (Exception e) {
            // Si hay error, devolver la fecha original
        }
        return fecha;
    }
    
    private String obtenerEmojiPorCategoria(String categoria) {
        switch (categoria.toLowerCase()) {
            case "tecnologia":
            case "tecnología":
                return "📱";
            case "hogar":
                return "🏠";
            case "ropa":
                return "👕";
            case "alimentos":
                return "🍔";
            case "deportes":
                return "⚽";
            default:
                return "📦";
        }
    }
}