/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author estra
 */
public class SubPanelHistorialGlobal extends javax.swing.JPanel {
    
    // ========== ATRIBUTOS ==========
    private PanelAdmin panelAdmin;
    private modelo.gestores.UsuarioManager usuarioManager;
    private modelo.gestores.ProductoManager productoManager;

    /**
     * Creates new form SubPanelHistorialGlobal
     */
    public SubPanelHistorialGlobal(PanelAdmin panelAdmin, 
                                modelo.gestores.UsuarioManager usuarioManager,
                                modelo.gestores.ProductoManager productoManager) {
        this.panelAdmin = panelAdmin;
        this.usuarioManager = usuarioManager;
        this.productoManager = productoManager;
    
        initComponents();
    
        // Configurar BoxLayout para panelHistorial (vertical)
        panelHistorial.setLayout(new javax.swing.BoxLayout(panelHistorial, javax.swing.BoxLayout.Y_AXIS));
    
        // Cargar historial global
        cargarHistorialGlobal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        lblTotalCompras = new javax.swing.JLabel();
        lblTotalVentas = new javax.swing.JLabel();
        lblTotalProductos = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        panelHistorial = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 590));
        setLayout(new java.awt.BorderLayout());

        panelSuperior.setBackground(new java.awt.Color(220, 53, 69));
        panelSuperior.setPreferredSize(new java.awt.Dimension(900, 60));
        panelSuperior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 10));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Historial Global de Compras");
        panelSuperior.add(lblTitulo);

        add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelInferior.setBackground(new java.awt.Color(236, 240, 241));
        panelInferior.setPreferredSize(new java.awt.Dimension(900, 80));
        panelInferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 15));

        lblTotalCompras.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTotalCompras.setForeground(new java.awt.Color(52, 73, 94));
        lblTotalCompras.setText("Total Compras: 0");
        panelInferior.add(lblTotalCompras);

        lblTotalVentas.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTotalVentas.setForeground(new java.awt.Color(39, 174, 96));
        lblTotalVentas.setText("Total Vendido: $0.00");
        panelInferior.add(lblTotalVentas);

        lblTotalProductos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblTotalProductos.setForeground(new java.awt.Color(102, 124, 234));
        lblTotalProductos.setText("Productos Vendidos: 0");
        panelInferior.add(lblTotalProductos);

        add(panelInferior, java.awt.BorderLayout.PAGE_END);

        panelHistorial.setBackground(new java.awt.Color(245, 245, 245));
        panelHistorial.setLayout(new javax.swing.BoxLayout(panelHistorial, javax.swing.BoxLayout.Y_AXIS));
        scrollPane.setViewportView(panelHistorial);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // ========== MÉTODOS ==========

    private void cargarHistorialGlobal() {
        // Limpiar panel
        panelHistorial.removeAll();
    
        java.util.List<modelo.entidades.Usuario> usuarios = usuarioManager.obtenerTodosUsuarios();
        java.util.List<CompraConUsuario> todasLasCompras = new java.util.ArrayList<>();
    
        // Recopilar todas las compras de todos los usuarios
        for (modelo.entidades.Usuario usuario : usuarios) {
            if (!usuario.esAdministrador()) { // Excluir compras del admin (si tuviera)
                modelo.gestores.HistorialManager historialManager = 
                    new modelo.gestores.HistorialManager(usuario.getNombre(), productoManager);
            
                java.util.List<modelo.entidades.Compra> comprasUsuario = historialManager.obtenerHistorial();
            
                for (modelo.entidades.Compra compra : comprasUsuario) {
                    todasLasCompras.add(new CompraConUsuario(usuario, compra));
                }
            }
        }
    
        if (todasLasCompras.isEmpty()) {
            // Mostrar mensaje de historial vacío
            javax.swing.JLabel lblVacio = new javax.swing.JLabel("No hay compras registradas aun");
            lblVacio.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
            lblVacio.setForeground(new java.awt.Color(150, 150, 150));
            lblVacio.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
        
            javax.swing.JLabel lblMensaje = new javax.swing.JLabel("Las compras de todos los usuarios apareceran aqui");
            lblMensaje.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 14));
            lblMensaje.setForeground(new java.awt.Color(120, 120, 120));
            lblMensaje.setAlignmentX(javax.swing.JComponent.CENTER_ALIGNMENT);
        
            panelHistorial.add(javax.swing.Box.createVerticalGlue());
            panelHistorial.add(lblVacio);
            panelHistorial.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
            panelHistorial.add(lblMensaje);
            panelHistorial.add(javax.swing.Box.createVerticalGlue());
        } else {
            // Ordenar por fecha (más recientes primero)
            // Por simplicidad, mostramos en orden inverso
            panelHistorial.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 15)));
        
            int numeroCompra = todasLasCompras.size();
            for (int i = todasLasCompras.size() - 1; i >= 0; i--) {
                CompraConUsuario compraConUsuario = todasLasCompras.get(i);
                panelHistorial.add(crearTarjetaCompra(compraConUsuario, numeroCompra));
                panelHistorial.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 15)));
                numeroCompra--;
            }
        }
    
        // Actualizar estadísticas
        actualizarEstadisticas(todasLasCompras);
    
        panelHistorial.revalidate();
        panelHistorial.repaint();
    }

    private javax.swing.JPanel crearTarjetaCompra(CompraConUsuario compraConUsuario, int numeroCompra) {
        modelo.entidades.Usuario usuario = compraConUsuario.usuario;
        modelo.entidades.Compra compra = compraConUsuario.compra;
    
        javax.swing.JPanel tarjeta = new javax.swing.JPanel();
        tarjeta.setLayout(new javax.swing.BoxLayout(tarjeta, javax.swing.BoxLayout.Y_AXIS));
        tarjeta.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200), 2),
            javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20)
        ));
        tarjeta.setBackground(java.awt.Color.WHITE);
        tarjeta.setMaximumSize(new java.awt.Dimension(850, Integer.MAX_VALUE));
    
        // ========== ENCABEZADO ==========
    
        javax.swing.JPanel panelEncabezado = new javax.swing.JPanel();
        panelEncabezado.setLayout(new java.awt.BorderLayout());
        panelEncabezado.setBackground(java.awt.Color.WHITE);
        panelEncabezado.setAlignmentX(javax.swing.JComponent.LEFT_ALIGNMENT);
    
        // Label de usuario y fecha
        javax.swing.JLabel lblInfo = new javax.swing.JLabel(
            String.format("Compra #%d - Usuario: %s - Fecha: %s", 
            numeroCompra, 
            usuario.getNombre(), 
            formatearFecha(compra.getFecha()))
        );
        lblInfo.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        lblInfo.setForeground(new java.awt.Color(50, 50, 50));
    
        panelEncabezado.add(lblInfo, java.awt.BorderLayout.WEST);
    
        tarjeta.add(panelEncabezado);
        tarjeta.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
    
        // Separador
        javax.swing.JSeparator separador1 = new javax.swing.JSeparator();
        separador1.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 1));
        separador1.setForeground(new java.awt.Color(220, 220, 220));
        tarjeta.add(separador1);
        tarjeta.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 15)));
    
        // ========== PRODUCTOS ==========
    
        java.util.List<modelo.entidades.ItemCarrito> productos = compra.getProductos();
    
        for (modelo.entidades.ItemCarrito item : productos) {
            javax.swing.JPanel panelProducto = crearPanelProducto(item);
            tarjeta.add(panelProducto);
            tarjeta.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 10)));
        }
    
        // ========== TOTAL ==========
    
        tarjeta.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
    
        javax.swing.JSeparator separador2 = new javax.swing.JSeparator();
        separador2.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 1));
        separador2.setForeground(new java.awt.Color(220, 220, 220));
        tarjeta.add(separador2);
        tarjeta.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 15)));
    
        javax.swing.JPanel panelTotal = new javax.swing.JPanel();
        panelTotal.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        panelTotal.setBackground(java.awt.Color.WHITE);
        panelTotal.setAlignmentX(javax.swing.JComponent.LEFT_ALIGNMENT);
    
        javax.swing.JLabel lblTotal = new javax.swing.JLabel(
            String.format("TOTAL: $%.2f", compra.getTotal())
        );
        lblTotal.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        lblTotal.setForeground(new java.awt.Color(40, 167, 69));
    
        panelTotal.add(lblTotal);
        tarjeta.add(panelTotal);
    
        return tarjeta;
    }

    private javax.swing.JPanel crearPanelProducto(modelo.entidades.ItemCarrito item) {
        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setLayout(new java.awt.BorderLayout(15, 0));
        panel.setBackground(new java.awt.Color(250, 250, 250));
        panel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230), 1),
            javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15)
        ));
        panel.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 60));
        panel.setAlignmentX(javax.swing.JComponent.LEFT_ALIGNMENT);
    
        modelo.entidades.Producto producto = item.getProducto();
    
        // Información
        javax.swing.JPanel panelInfo = new javax.swing.JPanel();
        panelInfo.setLayout(new javax.swing.BoxLayout(panelInfo, javax.swing.BoxLayout.Y_AXIS));
        panelInfo.setBackground(new java.awt.Color(250, 250, 250));
    
        javax.swing.JLabel lblNombre = new javax.swing.JLabel(producto.getNombre());
        lblNombre.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
        lblNombre.setAlignmentX(javax.swing.JComponent.LEFT_ALIGNMENT);
    
        javax.swing.JLabel lblCantidadPrecio = new javax.swing.JLabel(
            String.format("Cantidad: %d × $%.2f", item.getCantidad(), producto.getPrecio())
        );
        lblCantidadPrecio.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 12));
        lblCantidadPrecio.setForeground(new java.awt.Color(100, 100, 100));
        lblCantidadPrecio.setAlignmentX(javax.swing.JComponent.LEFT_ALIGNMENT);
    
        panelInfo.add(lblNombre);
        panelInfo.add(javax.swing.Box.createRigidArea(new java.awt.Dimension(0, 5)));
        panelInfo.add(lblCantidadPrecio);
    
        panel.add(panelInfo, java.awt.BorderLayout.CENTER);
    
        // Subtotal
        javax.swing.JLabel lblSubtotal = new javax.swing.JLabel(
            String.format("$%.2f", item.getSubtotal())
        );
        lblSubtotal.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 16));
        lblSubtotal.setForeground(new java.awt.Color(102, 126, 234));
    
        panel.add(lblSubtotal, java.awt.BorderLayout.EAST);
    
        return panel;
    }

    private void actualizarEstadisticas(java.util.List<CompraConUsuario> compras) {
        int totalCompras = compras.size();
        double totalVentas = 0.0;
        int totalProductosVendidos = 0;
    
        for (CompraConUsuario compraConUsuario : compras) {
            modelo.entidades.Compra compra = compraConUsuario.compra;
            totalVentas += compra.getTotal();
        
            for (modelo.entidades.ItemCarrito item : compra.getProductos()) {
                totalProductosVendidos += item.getCantidad();
            }
        }
     
        lblTotalCompras.setText("Total Compras: " + totalCompras);
        lblTotalVentas.setText(String.format("Total Vendido: $%.2f", totalVentas));
        lblTotalProductos.setText("Productos Vendidos: " + totalProductosVendidos);
    }

    private String formatearFecha(String fecha) {
        try {
            String[] partes = fecha.split("-");
            if (partes.length == 3) {
                return partes[2] + "/" + partes[1] + "/" + partes[0];
            }
        } catch (Exception e) {
            // Si hay error, devolver la fecha original
        }
        return fecha;
    }

    // Clase auxiliar para asociar usuario con compra
    private class CompraConUsuario {
        modelo.entidades.Usuario usuario;
        modelo.entidades.Compra compra;
    
        CompraConUsuario(modelo.entidades.Usuario usuario, modelo.entidades.Compra compra) {
            this.usuario = usuario;
            this.compra = compra;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalCompras;
    private javax.swing.JLabel lblTotalProductos;
    private javax.swing.JLabel lblTotalVentas;
    private javax.swing.JPanel panelHistorial;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
