/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;



/**
 *
 * @author estra
 */
/**
 * Ventana principal de la aplicación
 * Contiene el panel principal donde se cargan todas las vistas
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    // ========== ATRIBUTOS ==========
    private modelo.gestores.UsuarioManager usuarioManager;
    private modelo.gestores.ProductoManager productoManager;
    private modelo.entidades.Usuario usuarioActual;
    
    
    public VentanaPrincipal() {

        initComponents();
        
        
        //inicializar managers
        this.productoManager = new modelo.gestores.ProductoManager();
        this.usuarioManager = new modelo.gestores.UsuarioManager();
        this.usuarioActual = null;
        
        //crrrar ventana de la pantalla
        setLocationRelativeTo(null);
        
        //mostrar panel de inicio
        mostrarPanelInicio();
        
    }
    
    // METODOS PARA CAMBIAR PANELES
    private void mostrarPanel(javax.swing.JPanel panel) {
        panelPrincipal.removeAll();
        panelPrincipal.add(panel);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }
    
    public void mostrarPanelInicio(){
        mostrarPanel(new PanelInicio(this));
    }
    
    public void mostrarPanelLogin(){
        mostrarPanel(new PanelLogin(this));
    }
    
    public void mostrarPanelRegistro(){
        mostrarPanel(new PanelRegistro(this));
    }
    
    public void mostrarPanelTienda(){
        mostrarPanel(new PanelTienda(this, usuarioActual, productoManager));
    }
    
        // ========== GETTERS Y SETTERS ==========
    
    public modelo.gestores.UsuarioManager getUsuarioManager() {
        return usuarioManager;
    }
    
    public modelo.gestores.ProductoManager getProductoManager() {
        return productoManager;
    }
    
    public modelo.entidades.Usuario getUsuarioActual() {
        return usuarioActual;
    }
    
    public void setUsuarioActual(modelo.entidades.Usuario usuario) {
        this.usuarioActual = usuario;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tienda Virtual");
        setPreferredSize(new java.awt.Dimension(900, 650));
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
